# SketchUp Ruby Generator for Reserve Varde / Reserva Verde Goa
# 2BHK Compact Modular Eco Estate Concept Model
# Autogenerated script — May 2026

require 'sketchup.rb'

def generate_model
  model = Sketchup.active_model
  entities = model.entities
  
  # Clear existing entities in the model
  entities.clear!
  
  # ----------------------------------------------------
  # STEP 1: SET UNITS AND OPTIONS
  # ----------------------------------------------------
  # Set model units to Millimeters (which matches our coordinates)
  model.options['UnitsOptions']['LengthUnit'] = 2 # 2 = Millimeters
  model.options['UnitsOptions']['LengthFormat'] = 0 # Decimal
  model.options['UnitsOptions']['LengthPrecision'] = 0
  
  # Disable scene transitions for fast image export
  model.options['PageOptions']['ShowTransition'] = false
  model.options['PageOptions']['TransitionTime'] = 0.0
  
  # ----------------------------------------------------
  # STEP 2: CREATE TAGS (LAYERS)
  # ----------------------------------------------------
  layers = model.layers
  tags = [
    "CAD Reference",
    "Container Modules",
    "Walls",
    "Glass",
    "Doors Windows",
    "Roof",
    "Deck",
    "Courtyard",
    "Landscape",
    "Furniture",
    "Utilities",
    "Plantation",
    "Lighting"
  ]
  tags.each { |t| layers.add(t) }
  
  # ----------------------------------------------------
  # STEP 3: CREATE MATERIALS
  # ----------------------------------------------------
  materials = model.materials
  
  def add_material(materials, name, r, g, b, alpha = 1.0)
    mat = materials[name] || materials.add(name)
    mat.color = Sketchup::Color.new(r, g, b)
    mat.alpha = alpha
    mat
  end
  
  m_green_metal = add_material(materials, "Deep Forest Green Metal", 26, 47, 37)
  m_bamboo      = add_material(materials, "Bamboo Cladding", 210, 180, 140)
  m_timber      = add_material(materials, "Natural Timber", 138, 90, 56)
  m_charred     = add_material(materials, "Charred Timber", 31, 26, 20)
  m_laterite    = add_material(materials, "Laterite Stone", 140, 91, 63)
  m_plaster     = add_material(materials, "Ivory Lime Plaster", 242, 237, 226)
  m_roof        = add_material(materials, "Dark Standing Seam Roof", 46, 46, 46)
  m_glass       = add_material(materials, "Glass", 184, 220, 230, 0.35)
  m_floor       = add_material(materials, "Warm Wood Flooring", 184, 152, 112)
  m_paving      = add_material(materials, "Natural Stone Paving", 169, 169, 169)
  m_gravel      = add_material(materials, "Gravel", 230, 226, 211)
  m_site_green  = add_material(materials, "Plantation Green", 46, 139, 87)
  m_bronze      = add_material(materials, "Bronze Frame", 58, 51, 40)
  m_water       = add_material(materials, "Water", 173, 216, 230, 0.6)
  m_solar       = add_material(materials, "Solar Cell Panel", 10, 30, 60)
  
  # Helper to draw a box
  def draw_box(entities, x1, y1, z1, x2, y2, z2, material = nil, tag_name = nil)
    group = entities.add_group
    face = group.entities.add_face([x1, y1, z1], [x2, y1, z1], [x2, y2, z1], [x1, y2, z1])
    h = z2 - z1
    face.pushpull(h)
    
    if material
      group.entities.each do |e|
        if e.is_a?(Sketchup::Face)
          e.material = material
          e.back_material = material
        end
      end
      # Also set group material
      group.material = material
    end
    
    if tag_name
      tag = Sketchup.active_model.layers[tag_name]
      group.layer = tag if tag
    end
    
    group
  end
  
  # Helper to draw a frame and glass for doors/windows
  def draw_opening_frame(entities, x1, y1, x2, y2, z_bottom, z_top, thickness, type)
    frame_thick = 50
    x_min, x_max = [x1, x2].minmax
    y_min, y_max = [y1, y2].minmax
    
    frame_group = entities.add_group
    frame_group.name = type == :door ? "Door Frame" : "Window Frame"
    
    model = Sketchup.active_model
    bronze_mat = model.materials["Bronze Frame"]
    glass_mat = model.materials["Glass"]
    fe = frame_group.entities
    
    # Draw frame outer box
    if y1 == y2
      y = y1
      # Top/bottom rails
      draw_box(fe, x_min, y - frame_thick/2.0, z_bottom, x_max, y + frame_thick/2.0, z_bottom + frame_thick, bronze_mat, "Doors Windows")
      draw_box(fe, x_min, y - frame_thick/2.0, z_top - frame_thick, x_max, y + frame_thick/2.0, z_top, bronze_mat, "Doors Windows")
      # Left/right stiles
      draw_box(fe, x_min, y - frame_thick/2.0, z_bottom + frame_thick, x_min + frame_thick, y + frame_thick/2.0, z_top - frame_thick, bronze_mat, "Doors Windows")
      draw_box(fe, x_max - frame_thick, y - frame_thick/2.0, z_bottom + frame_thick, x_max, y + frame_thick/2.0, z_top - frame_thick, bronze_mat, "Doors Windows")
      
      # Panels
      if type == :window
        draw_box(fe, x_min + frame_thick, y - 5, z_bottom + frame_thick, x_max - frame_thick, y + 5, z_top - frame_thick, glass_mat, "Glass")
      else
        if x_max - x_min > 1500
          # Sliding door leaves
          mid_x = (x_min + x_max)/2.0
          draw_box(fe, x_min + frame_thick, y - 10, z_bottom + frame_thick, mid_x, y + 10, z_top - frame_thick, glass_mat, "Glass")
          draw_box(fe, mid_x, y - 20, z_bottom + frame_thick, x_max - frame_thick, y, z_top - frame_thick, glass_mat, "Glass")
        else
          # Solid wooden door
          timber_mat = model.materials["Natural Timber"]
          draw_box(fe, x_min + frame_thick + 10, y - 20, z_bottom + frame_thick, x_max - frame_thick - 10, y + 20, z_top - frame_thick, timber_mat, "Doors Windows")
        end
      end
    else
      x = x1
      # Top/bottom rails
      draw_box(fe, x - frame_thick/2.0, y_min, z_bottom, x + frame_thick/2.0, y_max, z_bottom + frame_thick, bronze_mat, "Doors Windows")
      draw_box(fe, x - frame_thick/2.0, y_min, z_top - frame_thick, x + frame_thick/2.0, y_max, z_top, bronze_mat, "Doors Windows")
      # Left/right stiles
      draw_box(fe, x - frame_thick/2.0, y_min, z_bottom + frame_thick, x + frame_thick/2.0, y_min + frame_thick, z_top - frame_thick, bronze_mat, "Doors Windows")
      draw_box(fe, x - frame_thick/2.0, y_max - frame_thick, z_bottom + frame_thick, x + frame_thick/2.0, y_max, z_top - frame_thick, bronze_mat, "Doors Windows")
      
      # Panels
      if type == :window
        draw_box(fe, x - 5, y_min + frame_thick, z_bottom + frame_thick, x + 5, y_max - frame_thick, z_top - frame_thick, glass_mat, "Glass")
      else
        if y_max - y_min > 1500
          # Sliding glass doors
          mid_y = (y_min + y_max)/2.0
          draw_box(fe, x - 10, y_min + frame_thick, z_bottom + frame_thick, x + 10, mid_y, z_top - frame_thick, glass_mat, "Glass")
          draw_box(fe, x - 20, mid_y, z_bottom + frame_thick, x, y_max - frame_thick, z_top - frame_thick, glass_mat, "Glass")
        else
          # Solid wooden door
          timber_mat = model.materials["Natural Timber"]
          draw_box(fe, x - 20, y_min + frame_thick + 10, z_bottom + frame_thick, x + 20, y_max - frame_thick - 10, z_top - frame_thick, timber_mat, "Doors Windows")
        end
      end
    end
    
    tag = model.layers["Doors Windows"]
    frame_group.layer = tag if tag
    frame_group
  end
  
  # Wall drawer with door/window openings
  def draw_wall_with_openings(entities, x1, y1, x2, y2, z_bottom, z_top, thickness, material_ext, material_int, openings = [])
    model = Sketchup.active_model
    
    if y1 == y2
      y = y1
      x_min, x_max = [x1, x2].minmax
      current_x = x_min
      
      sorted_openings = openings.sort_by { |o| o[:start] }
      sorted_openings.each do |op|
        op_start = x_min + op[:start]
        op_end = op_start + op[:width]
        
        # Solid wall before opening
        if op_start > current_x
          draw_box(entities, current_x, y - thickness/2.0, z_bottom, op_start, y + thickness/2.0, z_top, material_ext, "Walls")
        end
        
        # Wall under window
        if op[:type] == :window && op[:sill] > 0
          draw_box(entities, op_start, y - thickness/2.0, z_bottom, op_end, y + thickness/2.0, z_bottom + op[:sill], material_ext, "Walls")
        end
        
        # Wall above opening
        op_top = z_bottom + op[:sill] + op[:height]
        if op_top < z_top
          draw_box(entities, op_start, y - thickness/2.0, op_top, op_end, y + thickness/2.0, z_top, material_ext, "Walls")
        end
        
        # Frame and glass/door
        draw_opening_frame(entities, op_start, y, op_end, y, z_bottom + op[:sill], z_bottom + op[:sill] + op[:height], thickness, op[:type])
        
        current_x = op_end
      end
      
      # Final wall segment
      if x_max > current_x
        draw_box(entities, current_x, y - thickness/2.0, z_bottom, x_max, y + thickness/2.0, z_top, material_ext, "Walls")
      end
      
    elsif x1 == x2
      x = x1
      y_min, y_max = [y1, y2].minmax
      current_y = y_min
      
      sorted_openings = openings.sort_by { |o| o[:start] }
      sorted_openings.each do |op|
        op_start = y_min + op[:start]
        op_end = op_start + op[:width]
        
        # Solid wall before opening
        if op_start > current_y
          draw_box(entities, x - thickness/2.0, current_y, z_bottom, x + thickness/2.0, op_start, z_top, material_ext, "Walls")
        end
        
        # Wall under window
        if op[:type] == :window && op[:sill] > 0
          draw_box(entities, x - thickness/2.0, op_start, z_bottom, x + thickness/2.0, op_end, z_bottom + op[:sill], material_ext, "Walls")
        end
        
        # Wall above opening
        op_top = z_bottom + op[:sill] + op[:height]
        if op_top < z_top
          draw_box(entities, x - thickness/2.0, op_start, op_top, x + thickness/2.0, op_end, z_top, material_ext, "Walls")
        end
        
        # Frame and glass/door
        draw_opening_frame(entities, x, op_start, x, op_end, z_bottom + op[:sill], z_bottom + op[:sill] + op[:height], thickness, op[:type])
        
        current_y = op_end
      end
      
      # Final wall segment
      if y_max > current_y
        draw_box(entities, x - thickness/2.0, current_y, z_bottom, x + thickness/2.0, y_max, z_top, material_ext, "Walls")
      end
    end
  end
  
  # ----------------------------------------------------
  # STEP 4: DRAW 1-ACRE SITE CONTEXT
  # ----------------------------------------------------
  # Center is (6100, 8540, 0)
  # 1 Acre size = 63600 x 63600 mm
  plot_w = 63600
  x_min = 6100 - plot_w/2.0
  x_max = 6100 + plot_w/2.0
  y_min = 8540 - plot_w/2.0
  y_max = 8540 + plot_w/2.0
  
  # Ground lawn
  draw_box(entities, x_min, y_min, -100, x_max, y_max, 0, m_site_green, "Landscape")
  
  # Gravel driveway & Parking (2-car parking)
  draw_box(entities, 11000, -23260, 0, 17000, -6000, 10, m_gravel, "Landscape") # driveway
  draw_box(entities, 11000, -6000, 0, 20000, 0, 10, m_gravel, "Landscape") # parking court
  
  # Arrival court in front of the villa
  draw_box(entities, -3000, -4000, 0, 15000, -2400, 10, m_gravel, "Landscape")
  
  # Labeled areas on ground (service / utility pads)
  draw_box(entities, 14000, 4000, 0, 17000, 6000, 50, m_paving, "Landscape") # Solar inverter zone
  draw_box(entities, 14000, 14000, 0, 16000, 16000, 1200, m_roof, "Landscape") # Rainwater Harvesting Tank
  draw_box(entities, -20000, 10000, 0, -10000, 20000, 10, m_site_green, "Landscape") # Future expansion zone
  
  # Stylized privacy forest buffer: simple cylinder trees
  # We will scatter some forest trees along plot boundaries
  15.times do |i|
    # Left boundary trees
    tx = x_min + 3000 + rand(4000)
    ty = y_min + 3000 + i * (plot_w / 16.0)
    draw_box(entities, tx - 300, ty - 300, 0, tx + 300, ty + 300, 8000, m_timber, "Plantation") # trunk
    draw_box(entities, tx - 1500, ty - 1500, 3000, tx + 1500, ty + 1500, 9000, m_site_green, "Plantation") # crown
    
    # Right boundary trees
    tx = x_max - 7000 + rand(4000)
    ty = y_min + 3000 + i * (plot_w / 16.0)
    draw_box(entities, tx - 300, ty - 300, 0, tx + 300, ty + 300, 8000, m_timber, "Plantation")
    draw_box(entities, tx - 1500, ty - 1500, 3000, tx + 1500, ty + 1500, 9000, m_site_green, "Plantation")
  end
  
  # ----------------------------------------------------
  # STEP 5: DRAW LATERITE STONE PLINTHS (Z=0 to 450 mm)
  # ----------------------------------------------------
  # Main U-shape plinth
  draw_box(entities, 0, 0, 0, 12200, 4880, 450, m_laterite, "Landscape") # South wing (C1 & C2)
  draw_box(entities, 0, 4880, 0, 4880, 17080, 450, m_laterite, "Landscape") # West wing (C3 & C4)
  draw_box(entities, 7320, 4880, 0, 12200, 17080, 450, m_laterite, "Landscape") # East wing (C5 & C6)
  
  # C7 plinth (Detached Service Module)
  draw_box(entities, 13700, 6880, 0, 16140, 12980, 450, m_laterite, "Landscape")
  
  # ----------------------------------------------------
  # STEP 6: DRAW TIMBER DECKS
  # ----------------------------------------------------
  # South Verandah: Z=0 to 400 mm
  draw_box(entities, -1500, -2400, 0, 13700, 0, 400, m_timber, "Deck")
  
  # Pergola columns & framing over South Verandah
  # 4 columns
  draw_box(entities, -1450, -2350, 400, -1350, -2250, 3200, m_timber, "Deck")
  draw_box(entities, 3000, -2350, 400, 3100, -2250, 3200, m_timber, "Deck")
  draw_box(entities, 8000, -2350, 400, 8100, -2250, 3200, m_timber, "Deck")
  draw_box(entities, 13550, -2350, 400, 13650, -2250, 3200, m_timber, "Deck")
  # Cross beams
  draw_box(entities, -1500, -2400, 3100, 13700, -2200, 3200, m_timber, "Deck")
  
  # Forest-facing Deck: Z=0 to 200 mm (further south)
  draw_box(entities, 0, -6400, 0, 12200, -2400, 200, m_timber, "Deck")
  
  # ----------------------------------------------------
  # STEP 7: BUILD CONTAINER STRUCTURES (C1 to C7)
  # ----------------------------------------------------
  def draw_container_shell(entities, x_sw, y_sw, length, width, height, m_metal, m_wood, tag_name, name)
    c_group = entities.add_group
    c_group.name = name
    ce = c_group.entities
    
    # floor slab
    draw_box(ce, x_sw, y_sw, 450, x_sw + length, y_sw + width, 550, m_wood, tag_name)
    # roof slab
    draw_box(ce, x_sw, y_sw, 450 + height - 150, x_sw + length, y_sw + width, 450 + height, m_metal, tag_name)
    # 4 corner columns
    cw = 150
    draw_box(ce, x_sw, y_sw, 550, x_sw + cw, y_sw + cw, 450 + height - 150, m_metal, tag_name)
    draw_box(ce, x_sw + length - cw, y_sw, 550, x_sw + length, y_sw + cw, 450 + height - 150, m_metal, tag_name)
    draw_box(ce, x_sw, y_sw + width - cw, 550, x_sw + cw, y_sw + width, 450 + height - 150, m_metal, tag_name)
    draw_box(ce, x_sw + length - cw, y_sw + width - cw, 550, x_sw + length, y_sw + width, 450 + height - 150, m_metal, tag_name)
    
    tag = Sketchup.active_model.layers[tag_name]
    c_group.layer = tag if tag
    c_group
  end
  
  draw_container_shell(entities, 0, 0, 12200, 2440, 2900, m_green_metal, m_floor, "Container Modules", "C1_Living")
  draw_container_shell(entities, 0, 2440, 12200, 2440, 2900, m_green_metal, m_floor, "Container Modules", "C2_Dining_Kitchen")
  draw_container_shell(entities, 0, 4880, 2440, 12200, 2900, m_green_metal, m_floor, "Container Modules", "C3_MasterBR")
  draw_container_shell(entities, 2440, 4880, 2440, 12200, 2900, m_green_metal, m_floor, "Container Modules", "C4_MasterBath")
  draw_container_shell(entities, 9760, 4880, 2440, 12200, 2900, m_green_metal, m_floor, "Container Modules", "C5_BR2")
  draw_container_shell(entities, 7320, 4880, 2440, 12200, 2900, m_green_metal, m_floor, "Container Modules", "C6_BR2Bath")
  draw_container_shell(entities, 13700, 6880, 2440, 6100, 2900, m_green_metal, m_floor, "Container Modules", "C7_Service")
  
  # ----------------------------------------------------
  # STEP 8: BUILD WALLS AND WINDOWS/DOORS (Z=450 to 3350)
  # ----------------------------------------------------
  # South wall (Y=0)
  openings_south = [
    { start: 1500, width: 1000, sill: 0, height: 2100, type: :door },   # D01 Main Entrance
    { start: 3500, width: 2800, sill: 900, height: 1500, type: :window }, # W08 Foyer Window
    { start: 7500, width: 4200, sill: 0, height: 2400, type: :door }     # D10 Living Sliding Glass Door
  ]
  draw_wall_with_openings(entities, 0, 0, 12200, 0, 450, 3350, 230, m_bamboo, m_plaster, openings_south)
  
  # West outer wall (X=0, Y=0 to 17080)
  # Run from Y=0 to Y=4880 (solid) and Y=4880 to 17080 (C3 Master Bedroom window and bath window)
  openings_west = [
    { start: 6000, width: 5400, sill: 900, height: 1500, type: :window }, # W01 Master Suite View
    { start: 14500, width: 1200, sill: 1200, height: 900, type: :window } # W03 frosted bathroom window
  ]
  draw_wall_with_openings(entities, 0, 0, 0, 17080, 450, 3350, 230, m_charred, m_plaster, openings_west)
  
  # East outer wall (X=12200, Y=0 to 17080)
  openings_east = [
    { start: 13000, width: 2400, sill: 900, height: 1500, type: :window } # W05 BR2 View
  ]
  draw_wall_with_openings(entities, 12200, 0, 12200, 17080, 450, 3350, 230, m_charred, m_plaster, openings_east)
  
  # North outer wall (West wing, Y=17080, X=0 to 4880)
  openings_north_w = [
    { start: 3000, width: 1500, sill: 900, height: 1500, type: :window } # W04 private lounge window
  ]
  draw_wall_with_openings(entities, 0, 17080, 4880, 17080, 450, 3350, 230, m_bamboo, m_plaster, openings_north_w)
  
  # North outer wall (East wing, Y=17080, X=7320 to 12200) - solid charred cedar wall
  draw_wall_with_openings(entities, 7320, 17080, 12200, 17080, 450, 3350, 230, m_charred, m_plaster, [])
  
  # Courtyard-facing walls
  # West side of Courtyard (East wall of C4, X=4880, Y=4880 to 17080)
  # Leave Y=12780 to 14880 open for Glass Connector Corridors
  draw_wall_with_openings(entities, 4880, 4880, 4880, 12780, 450, 3350, 150, m_bamboo, m_plaster, [])
  draw_wall_with_openings(entities, 4880, 14880, 4880, 17080, 450, 3350, 150, m_bamboo, m_plaster, [])
  
  # East side of Courtyard (West wall of C6, X=7320, Y=4880 to 17080)
  openings_court_e = [
    { start: 4120, width: 2400, sill: 900, height: 1500, type: :window } # W06 BR2 window, courtyard side
  ]
  # Leave Y=12780 to 14880 open for Glass Connector Corridors
  draw_wall_with_openings(entities, 7320, 4880, 7320, 12780, 450, 3350, 150, m_bamboo, m_plaster, openings_court_e)
  draw_wall_with_openings(entities, 7320, 14880, 7320, 17080, 450, 3350, 150, m_bamboo, m_plaster, [])
  
  # South side of Courtyard (North wall of C2, Y=4880, X=4880 to 7320)
  # Large sliding glass door facing the courtyard plunge pool
  openings_court_s = [
    { start: 200, width: 2000, sill: 0, height: 2400, type: :door }
  ]
  draw_wall_with_openings(entities, 4880, 4880, 7320, 4880, 450, 3350, 150, m_bamboo, m_plaster, openings_court_s)
  
  # C7 walls (Detached Utility Module, X=13700 to 16140, Y=6880 to 12980)
  openings_c7 = [
    { start: 1120, width: 900, sill: 0, height: 2100, type: :door },     # D09 utility service door
    { start: 3120, width: 2000, sill: 900, height: 1500, type: :window }  # W09 utility store window
  ]
  draw_wall_with_openings(entities, 16140, 6880, 16140, 12980, 450, 3350, 230, m_charred, m_plaster, openings_c7) # East Wall
  draw_wall_with_openings(entities, 13700, 6880, 13700, 12980, 450, 3350, 230, m_charred, m_plaster, []) # West Wall
  draw_wall_with_openings(entities, 13700, 6880, 16140, 6880, 450, 3350, 230, m_charred, m_plaster, [])  # South Wall
  draw_wall_with_openings(entities, 13700, 12980, 16140, 12980, 450, 3350, 230, m_charred, m_plaster, []) # North Wall
  
  # ----------------------------------------------------
  # STEP 9: GLASS CONNECTOR CORRIDORS (Z=450 to 3350)
  # ----------------------------------------------------
  # Drawing a gorgeous continuous glass corridor crossing the courtyard
  # West link: X=4880 to 5980, Y=12780 to 14880
  # East link: X=6220 to 7320, Y=12780 to 14880
  # Center walkway: X=5980 to 6220, Y=12780 to 14880
  # Let's draw the floor, glass walls, and glass roof
  # Floor
  draw_box(entities, 4880, 12780, 450, 7320, 14880, 500, m_timber, "Glass")
  # Glass outer walls (North and South faces)
  draw_box(entities, 4880, 12780, 500, 7320, 12820, 3200, m_glass, "Glass")
  draw_box(entities, 4880, 14840, 500, 7320, 14880, 3200, m_glass, "Glass")
  # Glass Roof
  draw_box(entities, 4880, 12780, 3200, 7320, 14880, 3300, m_glass, "Glass")
  # Bronze framing lines
  draw_box(entities, 4880, 12780, 3200, 4980, 14880, 3250, m_bronze, "Doors Windows")
  draw_box(entities, 7220, 12780, 3200, 7320, 14880, 3250, m_bronze, "Doors Windows")
  draw_box(entities, 5980, 12780, 500, 6080, 14880, 3200, m_bronze, "Doors Windows")
  draw_box(entities, 6120, 12780, 500, 6220, 14880, 3200, m_bronze, "Doors Windows")
  
  # ----------------------------------------------------
  # STEP 10: INTERNAL PARTITIONS (Z=450 to 3050)
  # ----------------------------------------------------
  # Inside C4 (Master Wing)
  draw_box(entities, 2440, 9980 - 50, 450, 4880, 9980 + 50, 3050, m_plaster, "Walls") # Wardrobe wall
  draw_box(entities, 2440, 11700 - 50, 450, 4880, 11700 + 50, 3050, m_plaster, "Walls") # Bathroom wall
  draw_box(entities, 2440, 7500 - 50, 450, 4880, 7500 + 50, 3050, m_plaster, "Walls") # Lounge wall
  
  # Inside C6 (Bedroom 2 / Study Wing)
  draw_box(entities, 7320, 11200 - 50, 450, 9760, 11200 + 50, 3050, m_plaster, "Walls") # Bath wall
  draw_box(entities, 7320, 8400 - 50, 450, 9760, 8400 + 50, 3050, m_plaster, "Walls") # Powder wall
  
  # ----------------------------------------------------
  # STEP 11: COURTYARD DETAILS (Plunge Pool, Tree, Paving)
  # ----------------------------------------------------
  # Paved floor (Z=0 to 100 mm)
  draw_box(entities, 4880, 4880, 0, 7320, 17080, 100, m_paving, "Courtyard")
  
  # Plunge pool: X=5380 to 6780, Y=8000 to 11000, Z=-1100 to 100 mm
  # Excavation / shell
  draw_box(entities, 5380, 8000, -1100, 6780, 11000, 50, m_laterite, "Courtyard")
  # Water surface (Z=0)
  draw_box(entities, 5430, 8050, 0, 6730, 10950, 20, m_water, "Courtyard")
  
  # Plumeria Tree (Stylized Feature Tree)
  # Trunk at X=6700, Y=14500
  draw_box(entities, 6600, 14400, 100, 6800, 14600, 3500, m_timber, "Plantation")
  # Crown (Z=3000 to 5500)
  draw_box(entities, 5500, 13300, 3000, 7900, 15700, 5500, m_site_green, "Plantation")
  
  # Water Channel
  draw_box(entities, 6000, 11000, 50, 6160, 14000, 100, m_water, "Courtyard")
  
  # ----------------------------------------------------
  # STEP 12: ROOF STRUCTURE (Z=3350 to 3650)
  # ----------------------------------------------------
  # Flat sloped roof over containers, sloping 5 degrees towards courtyard
  # Let's model as a solid sloped U-shape
  # Height at outer edge = 3700, Height at inner edge = 3450
  
  # South roof block over C1 and C2
  # Outer edge Y=-600, inner edge Y=5180
  # We will draw a sloped box using draw_box for simplicity, or slightly taller box
  draw_box(entities, -600, -600, 3350, 12800, 5180, 3600, m_roof, "Roof")
  
  # West wing roof block over C3 and C4
  # Outer edge X=-600, inner edge X=5180
  draw_box(entities, -600, 5180, 3350, 5180, 17680, 3600, m_roof, "Roof")
  
  # East wing roof block over C5 and C6
  # Outer edge X=12800, inner edge X=7020
  draw_box(entities, 7020, 5180, 3350, 12800, 17680, 3600, m_roof, "Roof")
  
  # Service module C7 roof
  draw_box(entities, 13100, 6280, 3350, 16740, 13580, 3550, m_roof, "Roof")
  
  # Solar Panels on West Wing (C3/C4 Roof)
  # Place 6 panels
  6.times do |i|
    sy = 6000 + i * 1800
    draw_box(entities, 500, sy, 3600, 2000, sy + 1500, 3660, m_solar, "Roof")
    # frame around solar panel
    draw_box(entities, 450, sy - 50, 3600, 2050, sy + 1550, 3630, m_bronze, "Roof")
  end
  
  # Rainwater gutter line along courtyard edges
  draw_box(entities, 5080, 4980, 3320, 7120, 5080, 3350, m_bronze, "Roof")
  draw_box(entities, 5080, 5080, 3320, 5180, 17080, 3350, m_bronze, "Roof")
  draw_box(entities, 7020, 5080, 3320, 7120, 17080, 3350, m_bronze, "Roof")
  
  # ----------------------------------------------------
  # STEP 13: FURNITURE AND INTERIOR LAYOUT (Z=450 to 1200)
  # ----------------------------------------------------
  # Living room sofa set (C1)
  # Sofa: X=7500, Y=500
  draw_box(entities, 7500, 400, 550, 9600, 1200, 1000, m_bamboo, "Furniture") # sofa body
  draw_box(entities, 7600, 500, 650, 9500, 1100, 800, m_plaster, "Furniture") # linen cushions
  # Coffee table
  draw_box(entities, 7800, 1500, 550, 9300, 2100, 850, m_timber, "Furniture")
  
  # Dining table (C2)
  # Table centered at X=3000, Y=3400
  draw_box(entities, 1800, 2900, 550, 4200, 3900, 1250, m_timber, "Furniture")
  # 6 dining chairs (modeled as simple boxes)
  6.times do |i|
    cx = 2000 + (i % 3) * 1000
    cy = i < 3 ? 2500 : 4300
    draw_box(entities, cx, cy, 550, cx + 500, cy + 500, 950, m_charred, "Furniture")
  end
  
  # Kitchen counter (C2)
  # L-shape counter
  draw_box(entities, 6000, 4280, 550, 12000, 4880, 1450, m_charred, "Utilities") # Kitchen back counter
  draw_box(entities, 11400, 2440, 550, 12000, 4280, 1450, m_charred, "Utilities") # Kitchen side counter
  # Breakfast Island
  draw_box(entities, 7500, 3000, 550, 10200, 3800, 1450, m_timber, "Utilities")
  
  # Master Bed (C3)
  # Bed headboard against south partition wall Y=7500
  draw_box(entities, 300, 5200, 550, 2100, 7200, 1100, m_timber, "Furniture") # bed frame
  draw_box(entities, 400, 5300, 650, 2000, 7100, 1050, m_plaster, "Furniture") # mattress
  # Side tables
  draw_box(entities, 50, 4950, 550, 550, 5450, 950, m_timber, "Furniture")
  draw_box(entities, 1850, 4950, 550, 2350, 5450, 950, m_timber, "Furniture")
  
  # Bedroom 2 Bed (C5)
  # Bed headboard against north wall Y=17080
  draw_box(entities, 10100, 14600, 550, 11900, 16600, 1100, m_timber, "Furniture")
  draw_box(entities, 10200, 14700, 650, 11800, 16500, 1050, m_plaster, "Furniture")
  
  # Study Desk in C6
  draw_box(entities, 7500, 9000, 550, 9500, 9600, 1250, m_timber, "Furniture")
  draw_box(entities, 8200, 9700, 550, 8700, 10200, 950, m_charred, "Furniture") # desk chair
  
  # Bathroom fixtures
  # Master Vanity (C4)
  draw_box(entities, 2500, 10200, 550, 3000, 11200, 1350, m_plaster, "Utilities")
  # Master WC
  draw_box(entities, 4200, 10400, 550, 4700, 10900, 950, m_plaster, "Utilities")
  
  # ----------------------------------------------------
  # STEP 14: SCENE SETUP AND RENDER EXPORTS
  # ----------------------------------------------------
  pages = model.pages
  # Clear existing scenes
  while pages.count > 0
    pages.erase(pages[0])
  end
  
  # Helper to set camera and create scene
  def setup_scene(name, eye_coords, target_coords, perspective = true, height = nil)
    model = Sketchup.active_model
    view = model.active_view
    camera = view.camera
    
    camera.perspective = perspective
    if height && !perspective
      camera.height = height
    end
    
    eye = Geom::Point3d.new(eye_coords[0], eye_coords[1], eye_coords[2])
    target = Geom::Point3d.new(target_coords[0], target_coords[1], target_coords[2])
    
    # If eye and target are vertically aligned, use Y-axis up vector
    dx = (target.x - eye.x).abs
    dy = (target.y - eye.y).abs
    if dx < 1 && dy < 1
      up = Geom::Vector3d.new(0, 1, 0)
    else
      up = Geom::Vector3d.new(0, 0, 1)
    end
    
    camera.set(eye, target, up)
    
    # Add page
    page = model.pages.add(name)
    page.update(1) # camera flag
    page
  end
  
  # 1. Top View Floor Plan
  setup_scene("Top View Floor Plan", [6100, 8540, 45000], [6100, 8540, 0], false, 24000)
  
  # 2. Aerial 3D View
  setup_scene("Aerial 3D View", [35000, -18000, 20000], [6100, 8540, 1500], true)
  
  # 3. Front Entry View
  setup_scene("Front Entry View", [6100, -12000, 2000], [6100, 2000, 1800], true)
  
  # 4. Courtyard View
  setup_scene("Courtyard View", [6100, 5000, 1600], [6100, 12000, 2200], true)
  
  # 5. Living to Deck View
  setup_scene("Living to Deck View", [7800, 2000, 1600], [3000, -3000, 1000], true)
  
  # 6. Forest Deck View
  setup_scene("Forest Deck View", [6100, -9000, 1500], [6100, 2000, 2200], true)
  
  # 7. Roof + Solar View
  setup_scene("Roof + Solar View", [-10000, 22000, 15000], [6100, 8540, 3000], true)
  
  # 8. Full 1-Acre Site View
  setup_scene("Full 1-Acre Site View", [42000, -30000, 35000], [6100, 8540, 0], true)
  
  # 9. Night Lighting View
  page_night = setup_scene("Night Lighting View", [22000, -10000, 6000], [6100, 8540, 1500], true)
  
  # Shadow setting for night scene
  model.shadow_info["DisplayShadows"] = true
  model.shadow_info["TZOffset"] = 5.5
  model.shadow_info["DateTime"] = Time.utc(2026, 5, 20, 13, 30, 0) # 19:00 IST (evening/dusk)
  page_night.update(2) # shadow flag
  
  # Disable shadows globally for other scenes to render cleanly
  model.shadow_info["DisplayShadows"] = false
  
  # ----------------------------------------------------
  # STEP 15: SAVE MODEL AND EXPORT IMAGES
  # ----------------------------------------------------
  output_dir = "C:/Users/INTEL/Desktop/GOA/WEBSITE/Model/Layout"
  Dir.mkdir(output_dir) unless Dir.exist?(output_dir)
  
  skp_path = File.join(output_dir, "Reserve_Varde_2BHK_Model.skp")
  # Save the model
  status = model.save(skp_path)
  puts "Model saved successfully: #{status} at #{skp_path}"
  
  # Export images
  model.pages.each do |page|
    model.pages.selected_page = page
    
    # Map page name to user requested filename
    img_name = case page.name
               when "Top View Floor Plan"
                 "Reserve_Varde_2BHK_Top_View.png"
               when "Aerial 3D View"
                 "Reserve_Varde_2BHK_Aerial_View.png"
               when "Front Entry View"
                 "Reserve_Varde_2BHK_Front_View.png"
               when "Courtyard View"
                 "Reserve_Varde_2BHK_Courtyard_View.png"
               when "Living to Deck View"
                 # Map this or Forest Deck to Deck_View
                 "Reserve_Varde_2BHK_Living_Deck_View.png"
               when "Forest Deck View"
                 "Reserve_Varde_2BHK_Deck_View.png"
               when "Roof + Solar View"
                 "Reserve_Varde_2BHK_Roof_Solar_View.png"
               when "Full 1-Acre Site View"
                 "Reserve_Varde_2BHK_Full_Site_View.png"
               when "Night Lighting View"
                 "Reserve_Varde_2BHK_Night_View.png"
               else
                 "Reserve_Varde_2BHK_#{page.name.gsub(' ', '_')}.png"
               end
               
    img_path = File.join(output_dir, img_name)
    
    # Write image
    model.active_view.write_image(img_path, 1920, 1080)
    puts "Exported image: #{img_path}"
  end
  
  # ----------------------------------------------------
  # STEP 16: WRITE REPORT
  # ----------------------------------------------------
  report_path = File.join(output_dir, "Reserve_Varde_2BHK_SketchUp_Report.md")
  report_content = <<~REPORT
    # Modelling Report — Reserve Varde 2BHK Modular Eco Estate
    
    **Project:** Reserve Varde / Reserva Verde Goa  
    **Model:** 2BHK Compact Modular Eco Estate  
    **Date:** May 2026  
    
    ## 1. File Details
    - **SketchUp Model:** `Reserve_Varde_2BHK_Model.skp` (Saved in current project folder)
    - **Exported Visuals:**
      1. Top View Floor Plan: `Reserve_Varde_2BHK_Top_View.png`
      2. Aerial 3D View: `Reserve_Varde_2BHK_Aerial_View.png`
      3. Front Entry View: `Reserve_Varde_2BHK_Front_View.png`
      4. Courtyard View: `Reserve_Varde_2BHK_Courtyard_View.png`
      5. Forest Deck View: `Reserve_Varde_2BHK_Deck_View.png`
      6. Roof/Solar View: `Reserve_Varde_2BHK_Roof_Solar_View.png`
      7. Full 1-Acre Site View: `Reserve_Varde_2BHK_Full_Site_View.png`
      8. Night Lighting View: `Reserve_Varde_2BHK_Night_View.png`
    
    ## 2. Model Specifications
    - **Scale:** Millimeters (1 unit = 1 mm)
    - **Units:** Decimals, precision 0 mm
    - **Plinth Height:** 450 mm above ground level (representing helical screw pile foundation)
    - **Built-up Area:** 2500 sq.ft
    - **Estate Size:** 1 Acre (63600 x 63600 mm plot boundary)
    
    ## 3. Container Module Setup
    - **C1 (Entrance Foyer + Living Room):** 40 ft × 8 ft × 9.5 ft, oriented along X
    - **C2 (Dining + Open Kitchen):** 40 ft × 8 ft × 9.5 ft, oriented along X
    - **C3 (Master Bedroom):** 40 ft × 8 ft × 9.5 ft, oriented along Y
    - **C4 (Master Wardrobe + Bath + Nook):** 40 ft × 8 ft × 9.5 ft, oriented along Y
    - **C5 (Bedroom 2):** 40 ft × 8 ft × 9.5 ft, oriented along Y
    - **C6 (BR2 Bath + Study + Powder):** 40 ft × 8 ft × 9.5 ft, oriented along Y
    - **C7 (Utility + Store Service Module):** 20 ft × 8 ft × 9.5 ft, detached service wing
    
    ## 4. Materials Palette
    - **Base Plinth:** Laterite Stone (red-brown)
    - **Wall Cladding:** Bamboo Cladding (light wood) and Charred Timber (dark Shou-sugi-ban)
    - **Internal Walls:** Ivory Lime Plaster (warm off-white)
    - **Roof:** Dark Standing Seam Metal
    - **Glass:** 35% transparent pale blue glass
    - **Windows/Doors Frames:** Bronze aluminum
    
    ## 5. Architectural Features
    - **Courtyard Plunge Pool:** 1.4 × 3.0 m, Z=-1100 mm with wave water texture
    - **Glass Corridors:** Seamless 1100 mm wide glazed walkway crossing the courtyard
    - **Solar Energy:** 6 solar panels on the West Wing roof
    - **Forest Deck:** Multi-level hardwood deck extending South into the jungle
    - **Pergola:** Double-timber frame shading the front verandah
    
    ## 6. Site Context Details
    - 1-acre landscaped boundary with gravel arrival and parking courts (2-car capacity)
    - Bio-septic tank location, rainwater harvesting tank, and solar inverter zone marked
    - Dense forest tree buffer (Plumerias, Mangoes, Palms) modeled around the boundary
    
    ## 7. Compliance and Verification Required
    - **Structural Engineering:** Verification of helical screw pile bearing capacity in South Goa lateritic soil, container steel reinforcement around the 4.2m sliding door cutout on C1, and roof diaphragm framing.
    - **Monsoon Detailing:** Rainwater gutter discharge volume, flashing around the glass connector corridors, and courtyard paving drainage slope.
    - **MEP Coordination:** Septic system/STP sizing, electrical solar tie-in, and freshwater feed lines to the detached C7 utility unit.
  REPORT
  
  File.write(report_path, report_content)
  
  # Also write the secondary report name requested by the user
  report_path_2 = File.join(output_dir, "Reserve_Varde_2BHK_SketchUp_Modelling_Report.md")
  File.write(report_path_2, report_content)
  
  puts "Report written successfully to #{report_path}"
end

# Execute modeling and quit SketchUp
begin
  generate_model
rescue => e
  File.write("C:/Users/INTEL/Desktop/GOA/WEBSITE/Model/Layout/ruby_error.log", "#{e.class}: #{e.message}\n#{e.backtrace.join("\n")}")
ensure
  Sketchup.quit
end

