# SketchUp Lumion-Ready Ruby Generator for Reserve Varde / Reserva Varde Goa
# 2BHK Compact Modular Eco Estate Lumion Optimization Script
# Creates cleaned, grouped, and properly named material surfaces for Lumion import
# Autogenerated script — May 2026

require 'sketchup.rb'

def generate_lumion_ready_model
  model = Sketchup.active_model
  entities = model.entities
  
  # Clear existing entities in the model to start fresh
  entities.clear!
  
  # ----------------------------------------------------
  # STEP 1: SET UNITS AND OPTIONS
  # ----------------------------------------------------
  model.options['UnitsOptions']['LengthUnit'] = 2 # 2 = Millimeters
  model.options['UnitsOptions']['LengthFormat'] = 0 # Decimal
  model.options['UnitsOptions']['LengthPrecision'] = 0
  
  # Disable scene transitions for fast execution
  model.options['PageOptions']['ShowTransition'] = false
  model.options['PageOptions']['TransitionTime'] = 0.0
  
  # ----------------------------------------------------
  # STEP 2: CREATE TAGS (LAYERS)
  # ----------------------------------------------------
  layers = model.layers
  tags = [
    "RV_Container_Modules",
    "RV_Walls",
    "RV_Glass",
    "RV_Doors_Windows",
    "RV_Roof",
    "RV_Deck",
    "RV_Courtyard",
    "RV_Landscape_Base",
    "RV_Landscape_Foliage",
    "RV_Furniture",
    "RV_Utilities",
    "RV_Lighting",
    "RV_Annotations"
  ]
  tags.each { |t| layers.add(t) }
  
  # ----------------------------------------------------
  # STEP 3: CREATE LUMION-SPECIFIC MATERIALS (RV_ Prefix)
  # ----------------------------------------------------
  materials = model.materials
  
  def add_material(materials, name, r, g, b, alpha = 1.0)
    mat = materials[name] || materials.add(name)
    mat.color = Sketchup::Color.new(r, g, b)
    mat.alpha = alpha
    mat
  end
  
  m_charcoal_metal = add_material(materials, "RV_Charcoal_Metal", 38, 43, 49)          # Container frames, posts, downpipes
  m_cladding       = add_material(materials, "RV_Teak_Timber_Cladding", 195, 163, 115)   # Fine wall slats, privacy screens
  m_laterite       = add_material(materials, "RV_Laterite_Stone", 156, 73, 57)        # Raised plinth bases, piers, seating, steps
  m_glass          = add_material(materials, "RV_Glass_Dark_Reflective", 100, 149, 162, 0.40) # Widescreen windows, corridor glass
  m_deck           = add_material(materials, "RV_Deck_Timber", 175, 115, 60)            # Outdoor timber veranda and decks
  m_roof           = add_material(materials, "RV_Roof_Matte_Black", 46, 48, 51)         # Standing seam roofing metal
  m_gravel         = add_material(materials, "RV_Path_Gravel", 204, 197, 185)           # Gravel driveway, parking court, base drains
  m_grass          = add_material(materials, "RV_Terrain_Grass", 48, 87, 56)            # Standard site lawn terracing
  m_water          = add_material(materials, "RV_Water_PlungePool", 62, 163, 179, 0.55)  # Plunge pool water, courtyard channel
  m_solar          = add_material(materials, "RV_Solar_Panel", 16, 25, 45)              # Monocrystalline PV cells
  m_floor_wood     = add_material(materials, "RV_Interior_Warm_Floor", 168, 122, 82)    # Sofa frames, dining tables, beds, interior floors
  m_shrubs         = add_material(materials, "RV_Landscape_Shrubs", 26, 54, 34)         # Jungle forest boundary, bamboo stalks
  m_utility        = add_material(materials, "RV_Service_Utility", 24, 24, 24)          # Bio-Digester boxes, rainwater cisterns
  m_pebbles        = add_material(materials, "RV_Pebble_Swale", 150, 140, 130)           # Swale river rocks
  m_emissive       = add_material(materials, "RV_Emissive_Light", 255, 204, 102, 0.90)  # Path light glowing fixtures
  m_canvas         = add_material(materials, "RV_Furniture_Canvas", 232, 226, 214)      # Sand canvas fabric cushions
  
  # Helper to draw a box with front and back material assigned
  def draw_box(entities, x1, y1, z1, x2, y2, z2, material = nil, tag_name = nil)
    group = entities.add_group
    face = group.entities.add_face([x1, y1, z1], [x2, y1, z1], [x2, y2, z1], [x1, y2, z1])
    h = (z2 - z1).to_f
    face.pushpull(h) if h.abs > 0.01
    
    if material
      group.entities.each do |e|
        if e.is_a?(Sketchup::Face)
          e.material = material
          e.back_material = material
        end
      end
      group.material = material
    end
    
    if tag_name
      tag = Sketchup.active_model.layers[tag_name]
      group.layer = tag if tag
    end
    
    group
  end
  
  # Helper to draw a cylinder with front and back material assigned
  def draw_cylinder(entities, x, y, z_bottom, z_top, r, material = nil, tag_name = nil)
    group = entities.add_group
    ge = group.entities
    circle = ge.add_circle([x, y, z_bottom], [0, 0, 1], r, 16)
    face = ge.add_face(circle)
    h = (z_top - z_bottom).to_f
    face.pushpull(h) if h.abs > 0.01
    
    if material
      group.entities.each do |e|
        if e.is_a?(Sketchup::Face)
          e.material = material
          e.back_material = material
        end
      end
      group.material = material
    end
    
    if tag_name
      tag = Sketchup.active_model.layers[tag_name]
      group.layer = tag if tag
    end
    
    group
  end
  
  # Helper to draw vertical privacy screens
  def draw_privacy_screen(entities, x1, y1, x2, y2, z_bottom, z_top, slat_w, slat_d, spacing, material)
    dx = x2 - x1
    dy = y2 - y1
    length = Math.sqrt(dx*dx + dy*dy)
    return if length == 0
    
    num_slats = (length / spacing).floor
    ux = dx / length
    uy = dy / length
    
    num_slats.times do |i|
      sx = x1 + i * spacing * ux
      sy = y1 + i * spacing * uy
      draw_box(entities, sx - slat_w/2.0, sy - slat_d/2.0, z_bottom, sx + slat_w/2.0, sy + slat_d/2.0, z_top, material, "RV_Walls")
    end
  end
  
  # Helper to draw glass railings
  def draw_glass_railing(entities, x1, y1, x2, y2, z, material_post, material_glass)
    dx = x2 - x1
    dy = y2 - y1
    length = Math.sqrt(dx*dx + dy*dy)
    return if length == 0
    
    ux = dx / length
    uy = dy / length
    
    post_spacing = 1500.0
    num_posts = (length / post_spacing).floor + 1
    
    num_posts.times do |i|
      px = x1 + i * post_spacing * ux
      py = y1 + i * post_spacing * uy
      draw_box(entities, px - 20, py - 20, z, px + 20, py + 20, z + 1000, material_post, "RV_Deck")
      
      if i < num_posts - 1
        next_px = x1 + (i + 1) * post_spacing * ux
        next_py = y1 + (i + 1) * post_spacing * uy
        
        # Perpendicular vector to create thickness
        vx = -uy
        vy = ux
        t = 6.0 # half thickness (12mm total)
        
        # Draw a solid glass box
        group = entities.add_group
        ge = group.entities
        
        p1 = [px + 20*ux - t*vx, py + 20*uy - t*vy, z + 50]
        p2 = [next_px - 20*ux - t*vx, next_py - 20*uy - t*vy, z + 50]
        p3 = [next_px - 20*ux + t*vx, next_py - 20*uy + t*vy, z + 50]
        p4 = [px + 20*ux + t*vx, py + 20*uy + t*vy, z + 50]
        
        face = ge.add_face(p1, p2, p3, p4)
        face.pushpull(900) if face
        
        if material_glass
          ge.each do |e|
            if e.is_a?(Sketchup::Face)
              e.material = material_glass
              e.back_material = material_glass
            end
          end
          group.material = material_glass
        end
        
        tag = Sketchup.active_model.layers["RV_Glass"]
        group.layer = tag if tag
      end
    end
  end
  
  # Helper to draw stylized coconut palm trees (multi-height organic trunks)
  def draw_coconut_palm(entities, x, y, h_total, material_trunk, material_frond)
    palm_group = entities.add_group
    palm_group.name = "Coconut Palm"
    pe = palm_group.entities
    
    curr_x = x
    curr_y = y
    h = 0
    segs = 12
    seg_h = h_total / segs.to_f
    segs.times do |i|
      next_x = curr_x + i * 25 * Math.sin(i * 0.5)
      next_y = curr_y + i * 35 * Math.cos(i * 0.5)
      draw_box(pe, curr_x - 120, curr_y - 120, h, next_x + 120, next_y + 120, h + seg_h, material_trunk, "RV_Landscape_Foliage")
      curr_x = next_x
      curr_y = next_y
      h += seg_h
    end
    
    num_fronds = 14
    num_fronds.times do |j|
      angle = j * 2.0 * Math::PI / num_fronds
      fx = curr_x + Math.cos(angle) * 2700
      fy = curr_y + Math.sin(angle) * 2700
      
      vx = -Math.sin(angle)
      vy = Math.cos(angle)
      w = 140.0
      
      frond_group = pe.add_group
      fe = frond_group.entities
      
      p1 = [curr_x - w*vx, curr_y - w*vy, h - 500]
      p2 = [fx - w*vx, fy - w*vy, h - 100]
      p3 = [fx + w*vx, fy + w*vy, h - 100]
      p4 = [curr_x + w*vx, curr_y + w*vy, h - 500]
      
      face = fe.add_face(p1, p2, p3, p4)
      face.pushpull(60) if face
      
      if material_frond
        fe.each do |e|
          if e.is_a?(Sketchup::Face)
            e.material = material_frond
            e.back_material = material_frond
          end
        end
        frond_group.material = material_frond
      end
      
      tag = Sketchup.active_model.layers["RV_Landscape_Foliage"]
      frond_group.layer = tag if tag
    end
    
    tag = Sketchup.active_model.layers["RV_Landscape_Foliage"]
    palm_group.layer = tag if tag
  end
  
  # Helper to draw broadleaf jungle trees
  def draw_jungle_tree(entities, x, y, h_total, material_trunk, material_canopy)
    t_group = entities.add_group
    t_group.name = "Broadleaf Jungle Tree"
    te = t_group.entities
    
    # Trunk cylinder
    draw_cylinder(te, x, y, 0, h_total * 0.6, 250, material_trunk, "RV_Landscape_Foliage")
    
    # Canopy blocks
    draw_box(te, x - 1800, y - 1800, h_total * 0.5, x + 1800, y + 1800, h_total * 0.75, material_canopy, "RV_Landscape_Foliage")
    draw_box(te, x - 2200, y - 2200, h_total * 0.65, x + 2200, y + 2200, h_total * 0.9, material_canopy, "RV_Landscape_Foliage")
    draw_box(te, x - 1500, y - 1500, h_total * 0.85, x + 1500, y + 1500, h_total * 1.05, material_canopy, "RV_Landscape_Foliage")
    
    tag = Sketchup.active_model.layers["RV_Landscape_Foliage"]
    t_group.layer = tag if tag
  end
  
  # Helper to draw bamboo clusters
  def draw_bamboo_cluster(entities, x, y, num_stalks, material_bamboo)
    b_group = entities.add_group
    b_group.name = "Bamboo Cluster"
    be = b_group.entities
    
    num_stalks.times do |i|
      ox = x + rand(1500) - 750
      oy = y + rand(1500) - 750
      h = 5500 + rand(3000)
      draw_cylinder(be, ox, oy, 0, h, 25, material_bamboo, "RV_Landscape_Foliage")
      draw_box(be, ox - 900, oy - 900, h - 1800, ox + 900, oy + 900, h + 300, material_bamboo, "RV_Landscape_Foliage")
    end
    
    tag = Sketchup.active_model.layers["RV_Landscape_Foliage"]
    b_group.layer = tag if tag
  end
  
  # Helper to draw rock clusters
  def draw_rock_cluster(entities, x, y, num_rocks, material_stone)
    r_group = entities.add_group
    r_group.name = "Rock Cluster"
    re = r_group.entities
    
    num_rocks.times do |i|
      rx = x + rand(1000) - 500
      ry = y + rand(1000) - 500
      rw = 500 + rand(800)
      rd = 500 + rand(800)
      rh = 300 + rand(700)
      draw_box(re, rx - rw/2, ry - rd/2, 0, rx + rw/2, ry + rd/2, rh, material_stone, "RV_Landscape_Base")
    end
  end
  
  # Helper to draw path light pillars
  def draw_path_light(entities, x, y, z, material_bronze, material_gold)
    p_group = entities.add_group
    p_group.name = "Path Light"
    pe = p_group.entities
    draw_cylinder(pe, x, y, z, z + 600, 40, material_bronze, "RV_Lighting")
    draw_cylinder(pe, x, y, z + 600, z + 720, 38, material_gold, "RV_Lighting")
    draw_cylinder(pe, x, y, z + 720, z + 740, 45, material_bronze, "RV_Lighting")
  end
  
  # Helper to draw elegant annotation boards/signboards
  def draw_annotation_board(entities, x, y, z, height, width, title, description, material_post, material_board)
    s_group = entities.add_group
    s_group.name = "Annotation Board: #{title}"
    se = s_group.entities
    
    draw_box(se, x - 50, y - 50, z, x + 50, y + 50, z + height, material_post, "RV_Annotations")
    draw_box(se, x - width/2, y - 20, z + height - 400, x + width/2, y + 20, z + height, material_board, "RV_Annotations")
    m_charred = Sketchup.active_model.materials["RV_Service_Utility"]
    draw_box(se, x - width/2 + 20, y + 21, z + height - 380, x + width/2 - 20, y + 26, z + height - 20, m_charred, "RV_Annotations")
  end
  
  # Helper to draw a frame and glass for doors/windows
  def draw_opening_frame(entities, x1, y1, x2, y2, z_bottom, z_top, thickness, type)
    frame_thick = 40
    x_min, x_max = [x1, x2].minmax
    y_min, y_max = [y1, y2].minmax
    
    frame_group = entities.add_group
    frame_group.name = type == :door ? "Door Frame" : "Window Frame"
    
    model = Sketchup.active_model
    bronze_mat = model.materials["RV_Charcoal_Metal"]
    glass_mat = model.materials["RV_Glass_Dark_Reflective"]
    fe = frame_group.entities
    
    if y1 == y2
      y = y1
      draw_box(fe, x_min, y - frame_thick/2.0, z_bottom, x_max, y + frame_thick/2.0, z_bottom + frame_thick, bronze_mat, "RV_Doors_Windows")
      draw_box(fe, x_min, y - frame_thick/2.0, z_top - frame_thick, x_max, y + frame_thick/2.0, z_top, bronze_mat, "RV_Doors_Windows")
      draw_box(fe, x_min, y - frame_thick/2.0, z_bottom + frame_thick, x_min + frame_thick, y + frame_thick/2.0, z_top - frame_thick, bronze_mat, "RV_Doors_Windows")
      draw_box(fe, x_max - frame_thick, y - frame_thick/2.0, z_bottom + frame_thick, x_max, y + frame_thick/2.0, z_top - frame_thick, bronze_mat, "RV_Doors_Windows")
      
      if type == :window
        draw_box(fe, x_min + frame_thick, y - 5, z_bottom + frame_thick, x_max - frame_thick, y + 5, z_top - frame_thick, glass_mat, "RV_Glass")
      else
        mid_x = (x_min + x_max)/2.0
        draw_box(fe, x_min + frame_thick, y - 10, z_bottom + frame_thick, mid_x, y + 10, z_top - frame_thick, glass_mat, "RV_Glass")
        draw_box(fe, mid_x, y - 20, z_bottom + frame_thick, x_max - frame_thick, y, z_top - frame_thick, glass_mat, "RV_Glass")
        draw_box(fe, mid_x - 20, y - 25, z_bottom + frame_thick, mid_x + 20, y + 25, z_top - frame_thick, bronze_mat, "RV_Doors_Windows")
      end
    else
      x = x1
      draw_box(fe, x - frame_thick/2.0, y_min, z_bottom, x + frame_thick/2.0, y_max, z_bottom + frame_thick, bronze_mat, "RV_Doors_Windows")
      draw_box(fe, x - frame_thick/2.0, y_min, z_top - frame_thick, x + frame_thick/2.0, y_max, z_top, bronze_mat, "RV_Doors_Windows")
      draw_box(fe, x - frame_thick/2.0, y_min, z_bottom + frame_thick, x + frame_thick/2.0, y_min + frame_thick, z_top - frame_thick, bronze_mat, "RV_Doors_Windows")
      draw_box(fe, x - frame_thick/2.0, y_max - frame_thick, z_bottom + frame_thick, x + frame_thick/2.0, y_max, z_top - frame_thick, bronze_mat, "RV_Doors_Windows")
      
      if type == :window
        draw_box(fe, x - 5, y_min + frame_thick, z_bottom + frame_thick, x + 5, y_max - frame_thick, z_top - frame_thick, glass_mat, "RV_Glass")
      else
        mid_y = (y_min + y_max)/2.0
        draw_box(fe, x - 10, y_min + frame_thick, z_bottom + frame_thick, x + 10, mid_y, z_top - frame_thick, glass_mat, "RV_Glass")
        draw_box(fe, x - 20, mid_y, z_bottom + frame_thick, x, y_max - frame_thick, z_top - frame_thick, glass_mat, "RV_Glass")
        draw_box(fe, x - 25, mid_y - 20, z_bottom + frame_thick, x + 25, mid_y + 20, z_top - frame_thick, bronze_mat, "RV_Doors_Windows")
      end
    end
    
    tag = model.layers["RV_Doors_Windows"]
    frame_group.layer = tag if tag
    frame_group
  end
  
  # Wall drawer with openings and detailed fine timber cladding overlay strips
  def draw_wall_with_openings_and_cladding(entities, x1, y1, x2, y2, z_bottom, z_top, thickness, material_ext, material_int, openings = [])
    if y1 == y2
      y = y1
      x_min, x_max = [x1, x2].minmax
      current_x = x_min
      
      sorted_openings = openings.sort_by { |o| o[:start] }
      sorted_openings.each do |op|
        op_start = x_min + op[:start]
        op_end = op_start + op[:width]
        
        if op_start > current_x
          draw_box(entities, current_x, y - thickness/2.0, z_bottom, op_start, y + thickness/2.0, z_top, material_ext, "RV_Walls")
          slat_spacing = 150.0
          slat_cnt = ((op_start - current_x) / slat_spacing).floor
          slat_cnt.times do |k|
            slat_x = current_x + k * slat_spacing
            draw_box(entities, slat_x - 20, y - thickness/2.0 - 10, z_bottom, slat_x + 20, y - thickness/2.0, z_top, Sketchup.active_model.materials["RV_Teak_Timber_Cladding"], "RV_Walls")
          end
        end
        
        if op[:type] == :window && op[:sill] > 0
          draw_box(entities, op_start, y - thickness/2.0, z_bottom, op_end, y + thickness/2.0, z_bottom + op[:sill], material_ext, "RV_Walls")
        end
        
        op_top = z_bottom + op[:sill] + op[:height]
        if op_top < z_top
          draw_box(entities, op_start, y - thickness/2.0, op_top, op_end, y + thickness/2.0, z_top, material_ext, "RV_Walls")
        end
        
        draw_opening_frame(entities, op_start, y, op_end, y, z_bottom + op[:sill], z_bottom + op[:sill] + op[:height], thickness, op[:type])
        current_x = op_end
      end
      
      if x_max > current_x
        draw_box(entities, current_x, y - thickness/2.0, z_bottom, x_max, y + thickness/2.0, z_top, material_ext, "RV_Walls")
        slat_spacing = 150.0
        slat_cnt = ((x_max - current_x) / slat_spacing).floor
        slat_cnt.times do |k|
          slat_x = current_x + k * slat_spacing
          draw_box(entities, slat_x - 20, y - thickness/2.0 - 10, z_bottom, slat_x + 20, y - thickness/2.0, z_top, Sketchup.active_model.materials["RV_Teak_Timber_Cladding"], "RV_Walls")
        end
      end
      
    elsif x1 == x2
      x = x1
      y_min, y_max = [y1, y2].minmax
      current_y = y_min
      
      sorted_openings = openings.sort_by { |o| o[:start] }
      sorted_openings.each do |op|
        op_start = y_min + op[:start]
        op_end = op_start + op[:width]
        
        if op_start > current_y
          draw_box(entities, x - thickness/2.0, current_y, z_bottom, x + thickness/2.0, op_start, z_top, material_ext, "RV_Walls")
          slat_spacing = 150.0
          slat_cnt = ((op_start - current_y) / slat_spacing).floor
          slat_cnt.times do |k|
            slat_y = current_y + k * slat_spacing
            draw_box(entities, x - thickness/2.0 - 10, slat_y - 20, z_bottom, x - thickness/2.0, slat_y + 20, z_top, Sketchup.active_model.materials["RV_Teak_Timber_Cladding"], "RV_Walls")
          end
        end
        
        if op[:type] == :window && op[:sill] > 0
          draw_box(entities, x - thickness/2.0, op_start, z_bottom, x + thickness/2.0, op_end, z_bottom + op[:sill], material_ext, "RV_Walls")
        end
        
        op_top = z_bottom + op[:sill] + op[:height]
        if op_top < z_top
          draw_box(entities, x - thickness/2.0, op_start, op_top, x + thickness/2.0, op_end, z_top, material_ext, "RV_Walls")
        end
        
        draw_opening_frame(entities, x, op_start, x, op_end, z_bottom + op[:sill], z_bottom + op[:sill] + op[:height], thickness, op[:type])
        current_y = op_end
      end
      
      if y_max > current_y
        draw_box(entities, x - thickness/2.0, current_y, z_bottom, x + thickness/2.0, y_max, z_top, material_ext, "RV_Walls")
        slat_spacing = 150.0
        slat_cnt = ((y_max - current_y) / slat_spacing).floor
        slat_cnt.times do |k|
          slat_y = current_y + k * slat_spacing
          draw_box(entities, x - thickness/2.0 - 10, slat_y - 20, z_bottom, x - thickness/2.0, slat_y + 20, z_top, Sketchup.active_model.materials["RV_Teak_Timber_Cladding"], "RV_Walls")
        end
      end
    end
  end
  
  # ----------------------------------------------------
  # STEP 4: DRAW MULTI-LEVEL SITE CONTEXT
  # ----------------------------------------------------
  plot_w = 64000
  x_min = 6100 - plot_w/2.0
  x_max = 6100 + plot_w/2.0
  y_min = 8540 - plot_w/2.0
  y_max = 8540 + plot_w/2.0
  
  # Grass Terrain Terraces
  draw_box(entities, x_min, y_min, -300, x_max, -4000, -200, m_grass, "RV_Landscape_Base") # Low
  draw_box(entities, x_min, -4000, -200, x_max, 17080, 0, m_grass, "RV_Landscape_Base") # Mid
  draw_box(entities, x_min, 17080, 0, x_max, y_max, 250, m_grass, "RV_Landscape_Base") # High
  
  # Laterite Retaining Walls
  draw_box(entities, x_min, -4150, -200, x_max, -3850, 50, m_laterite, "RV_Landscape_Base")
  draw_box(entities, x_min, 16930, 0, x_max, 17230, 300, m_laterite, "RV_Landscape_Base")
  
  # Organic Curved Step Pathway
  15.times do |i|
    t = i / 14.0
    cx = 12000 - t * 8500 + 400 * Math.sin(t * Math::PI * 2)
    cy = -7500 + t * 7000
    draw_box(entities, cx - 600, cy - 600, 10, cx + 600, cy + 600, 40, m_laterite, "RV_Landscape_Base") # paved laterite steps
    
    if i % 3 == 0
      side = i % 2 == 0 ? 1 : -1
      lx = cx + side * 900
      ly = cy
      draw_path_light(entities, lx, ly, 20, m_charcoal_metal, m_emissive)
    end
  end
  
  # Bioswale / Pebbled Swale Feature
  draw_box(entities, -4000, -7000, -180, 1000, -3000, -100, m_gravel, "RV_Landscape_Base")
  draw_box(entities, -3800, -6800, -100, 800, -3200, -50, m_pebbles, "RV_Landscape_Base")
  draw_box(entities, -3500, -6500, -70, 500, -3500, -60, m_water, "RV_Landscape_Base")
  
  # Swale boulders
  draw_rock_cluster(entities, -3000, -5000, 4, m_laterite)
  
  # Winding Gravel Driveway
  draw_box(entities, 9000, -23460, -200, 15000, -8000, -190, m_gravel, "RV_Landscape_Base")
  draw_box(entities, 9000, -8000, -200, 18000, -2400, -190, m_gravel, "RV_Landscape_Base")
  
  # Laterite Piers & sliding wood gate
  draw_box(entities, 9000, -22000, -200, 9800, -21200, 2400, m_laterite, "RV_Landscape_Base")
  draw_box(entities, 14200, -22000, -200, 15000, -21200, 2400, m_laterite, "RV_Landscape_Base")
  draw_box(entities, 9800, -21700, 100, 13800, -21600, 1800, m_deck, "RV_Landscape_Base") # Gate wood
  
  # Welcome Signage
  draw_annotation_board(entities, 15800, -21200, -200, 1800, 1500, "Reserva Varde", "Eco Estate", m_laterite, m_deck)
  
  # Meditation Firepit Zone
  draw_box(entities, -17000, 23000, 250, -13000, 27000, 270, m_laterite, "RV_Landscape_Base")
  draw_box(entities, -15400, 24600, 270, -14600, 25400, 570, m_laterite, "RV_Landscape_Base")
  draw_box(entities, -15250, 24750, 300, -14750, 25250, 590, m_utility, "RV_Landscape_Base")
  draw_box(entities, -15100, 24900, 590, -14900, 25100, 640, m_emissive, "RV_Landscape_Base")
  
  # Seating logs
  draw_box(entities, -16500, 24800, 270, -16000, 25200, 700, m_deck, "RV_Landscape_Base")
  draw_box(entities, -14000, 24800, 270, -13500, 25200, 700, m_deck, "RV_Landscape_Base")
  draw_box(entities, -15200, 26000, 270, -14800, 26500, 700, m_deck, "RV_Landscape_Base")
  draw_box(entities, -15200, 23500, 270, -14800, 24000, 700, m_deck, "RV_Landscape_Base")
  
  # Stepping stones
  12.times do |i|
    sx = -1000 - i * 1100
    sy = 12000 + i * 1000
    draw_box(entities, sx - 300, sy - 300, 10, sx + 300, sy + 300, 30, m_laterite, "RV_Landscape_Base")
  end
  
  # Landscaped Utility Zone
  draw_box(entities, 14000, 3500, 0, 15500, 5000, 1100, m_utility, "RV_Utilities") # STP
  draw_box(entities, 14050, 3550, 1100, 15450, 4950, 1150, m_charcoal_metal, "RV_Utilities")
  draw_annotation_board(entities, 13000, 4250, 0, 1200, 1000, "STP System", "Bio-Digester", m_deck, m_utility)
  
  draw_cylinder(entities, 14800, 6500, 0, 1800, 900, m_utility, "RV_Utilities") # Cistern
  draw_cylinder(entities, 14800, 6500, 1800, 1900, 920, m_charcoal_metal, "RV_Utilities")
  draw_annotation_board(entities, 13000, 6500, 0, 1200, 1000, "Rainwater", "Cistern", m_deck, m_utility)
  
  draw_box(entities, 14000, 7500, 0, 15200, 9000, 800, m_utility, "RV_Utilities") # Greywater reuse
  draw_box(entities, 14050, 7550, 800, 15150, 8950, 840, m_charcoal_metal, "RV_Utilities")
  
  # Utility Screen
  draw_privacy_screen(entities, 13500, 3000, 13500, 9500, 0, 2200, 40, 60, 200, m_deck)
  
  # ----------------------------------------------------
  # STEP 5: LATERITE STONE PLINTHS (Z=0 to 450)
  # ----------------------------------------------------
  draw_box(entities, 0, 0, 0, 12200, 4880, 450, m_laterite, "RV_Landscape_Base") # South
  draw_box(entities, 0, 4880, 0, 4880, 17080, 450, m_laterite, "RV_Landscape_Base") # West
  draw_box(entities, 7320, 4880, 0, 12200, 17080, 450, m_laterite, "RV_Landscape_Base") # East
  draw_box(entities, 13700, 6880, 0, 16140, 12980, 450, m_laterite, "RV_Landscape_Base") # C7
  
  # Base Plinth Gravel drains
  draw_box(entities, -300, -300, 0, 12500, 5180, 20, m_gravel, "RV_Landscape_Base")
  draw_box(entities, -300, 5180, 0, 5180, 17380, 20, m_gravel, "RV_Landscape_Base")
  draw_box(entities, 7020, 5180, 0, 12500, 17380, 20, m_gravel, "RV_Landscape_Base")
  
  # ----------------------------------------------------
  # STEP 6: UPGRADED DECK PLANKING
  # ----------------------------------------------------
  draw_box(entities, -1500, -2400, 0, 13700, 0, 400, m_deck, "RV_Deck")
  
  # Verandah pergola
  draw_box(entities, -1450, -2350, 400, -1350, -2250, 3200, m_deck, "RV_Deck")
  draw_box(entities, 3000, -2350, 400, 3100, -2250, 3200, m_deck, "RV_Deck")
  draw_box(entities, 8000, -2350, 400, 8100, -2250, 3200, m_deck, "RV_Deck")
  draw_box(entities, 13550, -2350, 400, 13650, -2250, 3200, m_deck, "RV_Deck")
  draw_box(entities, -1500, -2400, 3100, 13700, -2200, 3200, m_deck, "RV_Deck")
  50.times do |s|
    sx = -1500 + s * 300
    draw_box(entities, sx - 20, -2400, 3200, sx + 20, 0, 3240, m_deck, "RV_Deck")
  end
  
  # Forest Deck
  draw_box(entities, 0, -6400, 0, 12200, -2400, 200, m_deck, "RV_Deck")
  draw_glass_railing(entities, 0, -6350, 12200, -6350, 200, m_charcoal_metal, m_glass)
  
  # Loungers
  draw_box(entities, 2000, -5000, 200, 2700, -3100, 400, m_deck, "RV_Furniture")
  draw_box(entities, 2100, -4900, 400, 2600, -3200, 500, m_canvas, "RV_Furniture")
  draw_box(entities, 3500, -5000, 200, 4200, -3100, 400, m_deck, "RV_Furniture")
  draw_box(entities, 3600, -4900, 400, 4100, -3200, 500, m_canvas, "RV_Furniture")
  
  # Dining table
  draw_box(entities, 7000, -5000, 200, 9200, -4000, 900, m_deck, "RV_Furniture")
  6.times do |i|
    cx = 7200 + (i % 3) * 750
    cy = i < 3 ? -5400 : -3700
    draw_box(entities, cx, cy, 200, cx + 450, cy + 450, 600, m_utility, "RV_Furniture") # charred wood frames
    draw_box(entities, cx + 20, cy + 20, 600, cx + 430, cy + 430, 640, m_canvas, "RV_Furniture")
  end
  
  # ----------------------------------------------------
  # STEP 7: BUILD SOLID CONTAINER CORES AND FRAMES (C1 to C7)
  # ----------------------------------------------------
  def draw_premium_container(entities, x_sw, y_sw, length, width, height, m_metal, m_wood, tag_name, name)
    c_group = entities.add_group
    c_group.name = name
    ce = c_group.entities
    
    draw_box(ce, x_sw, y_sw, 450, x_sw + length, y_sw + width, 550, m_wood, tag_name)
    draw_box(ce, x_sw, y_sw, 450 + height - 150, x_sw + length, y_sw + width, 450 + height, m_metal, tag_name)
    
    cw = 150
    draw_box(ce, x_sw, y_sw, 550, x_sw + cw, y_sw + cw, 450 + height - 150, m_metal, tag_name)
    draw_box(ce, x_sw + length - cw, y_sw, 550, x_sw + length, y_sw + cw, 450 + height - 150, m_metal, tag_name)
    draw_box(ce, x_sw, y_sw + width - cw, 550, x_sw + cw, y_sw + width, 450 + height - 150, m_metal, tag_name)
    draw_box(ce, x_sw + length - cw, y_sw + width - cw, 550, x_sw + length, y_sw + width, 450 + height - 150, m_metal, tag_name)
    
    draw_box(ce, x_sw, y_sw, 450, x_sw + length, y_sw + cw, 550, m_metal, tag_name)
    draw_box(ce, x_sw, y_sw + width - cw, 450, x_sw + length, y_sw + width, 550, m_metal, tag_name)
    draw_box(ce, x_sw, y_sw, 450 + height - 150, x_sw + length, y_sw + cw, 450 + height, m_metal, tag_name)
    draw_box(ce, x_sw, y_sw + width - cw, 450 + height - 150, x_sw + length, y_sw + width, 450 + height, m_metal, tag_name)
    
    tag = Sketchup.active_model.layers[tag_name]
    c_group.layer = tag if tag
    c_group
  end
  
  draw_premium_container(entities, 0, 0, 12200, 2440, 2900, m_charcoal_metal, m_floor_wood, "RV_Container_Modules", "C1_Living")
  draw_premium_container(entities, 0, 2440, 12200, 2440, 2900, m_charcoal_metal, m_floor_wood, "RV_Container_Modules", "C2_Dining_Kitchen")
  draw_premium_container(entities, 0, 4880, 2440, 12200, 2900, m_charcoal_metal, m_floor_wood, "RV_Container_Modules", "C3_MasterBR")
  draw_premium_container(entities, 2440, 4880, 2440, 12200, 2900, m_charcoal_metal, m_floor_wood, "RV_Container_Modules", "C4_MasterBath")
  draw_premium_container(entities, 9760, 4880, 2440, 12200, 2900, m_charcoal_metal, m_floor_wood, "RV_Container_Modules", "C5_BR2")
  draw_premium_container(entities, 7320, 4880, 2440, 12200, 2900, m_charcoal_metal, m_floor_wood, "RV_Container_Modules", "C6_BR2Bath")
  draw_premium_container(entities, 13700, 6880, 2440, 6100, 2900, m_charcoal_metal, m_floor_wood, "RV_Container_Modules", "C7_Service")
  
  # ----------------------------------------------------
  # STEP 8: BUILD WALLS & SLIDING GLAZING OPENINGS
  # ----------------------------------------------------
  openings_south = [
    { start: 1500, width: 1000, sill: 0, height: 2100, type: :door },
    { start: 3500, width: 2800, sill: 900, height: 1500, type: :window },
    { start: 7500, width: 4200, sill: 0, height: 2400, type: :door }
  ]
  draw_wall_with_openings_and_cladding(entities, 0, 0, 3500, 0, 450, 3350, 230, m_utility, m_utility, [openings_south[0]])
  draw_wall_with_openings_and_cladding(entities, 3500, 0, 12200, 0, 450, 3350, 230, m_cladding, m_utility, [openings_south[1], openings_south[2]])
  
  openings_west = [
    { start: 6000, width: 5400, sill: 900, height: 1500, type: :window },
    { start: 14500, width: 1200, sill: 1200, height: 900, type: :window }
  ]
  draw_wall_with_openings_and_cladding(entities, 0, 0, 0, 17080, 450, 3350, 230, m_utility, m_utility, openings_west)
  
  # Sun louvre privacy screen (C3)
  draw_privacy_screen(entities, -100, 6000, -100, 11400, 550, 3200, 40, 60, 250, m_deck)
  
  openings_east = [
    { start: 13000, width: 2400, sill: 900, height: 1500, type: :window }
  ]
  draw_wall_with_openings_and_cladding(entities, 12200, 0, 12200, 17080, 450, 3350, 230, m_utility, m_utility, openings_east)
  
  openings_north_w = [
    { start: 3000, width: 1500, sill: 900, height: 1500, type: :window }
  ]
  draw_wall_with_openings_and_cladding(entities, 0, 17080, 4880, 17080, 450, 3350, 230, m_cladding, m_utility, openings_north_w)
  draw_wall_with_openings_and_cladding(entities, 7320, 17080, 12200, 17080, 450, 3350, 230, m_utility, m_utility, [])
  
  draw_wall_with_openings_and_cladding(entities, 4880, 4880, 4880, 12780, 450, 3350, 150, m_cladding, m_utility, [])
  draw_wall_with_openings_and_cladding(entities, 4880, 14880, 4880, 17080, 450, 3350, 150, m_cladding, m_utility, [])
  
  openings_court_e = [
    { start: 4120, width: 2400, sill: 900, height: 1500, type: :window }
  ]
  draw_wall_with_openings_and_cladding(entities, 7320, 4880, 7320, 12780, 450, 3350, 150, m_cladding, m_utility, openings_court_e)
  draw_wall_with_openings_and_cladding(entities, 7320, 14880, 7320, 17080, 450, 3350, 150, m_cladding, m_utility, [])
  
  openings_court_s = [
    { start: 200, width: 2000, sill: 0, height: 2400, type: :door }
  ]
  draw_wall_with_openings_and_cladding(entities, 4880, 4880, 7320, 4880, 450, 3350, 150, m_cladding, m_utility, openings_court_s)
  
  # C7
  openings_c7 = [
    { start: 1120, width: 900, sill: 0, height: 2100, type: :door },
    { start: 3120, width: 2000, sill: 900, height: 1500, type: :window }
  ]
  draw_wall_with_openings_and_cladding(entities, 16140, 6880, 16140, 12980, 450, 3350, 230, m_utility, m_utility, openings_c7)
  draw_wall_with_openings_and_cladding(entities, 13700, 6880, 13700, 12980, 450, 3350, 230, m_utility, m_utility, [])
  draw_wall_with_openings_and_cladding(entities, 13700, 6880, 16140, 6880, 450, 3350, 230, m_utility, m_utility, [])
  draw_wall_with_openings_and_cladding(entities, 13700, 12980, 16140, 12980, 450, 3350, 230, m_utility, m_utility, [])
  
  # ----------------------------------------------------
  # STEP 9: GLAZED CONNECTOR CORRIDORS (Z=450 to 3350)
  # ----------------------------------------------------
  draw_box(entities, 4880, 12780, 450, 7320, 14880, 500, m_deck, "RV_Glass")
  draw_box(entities, 4880, 12780, 500, 7320, 12820, 3200, m_glass, "RV_Glass")
  draw_box(entities, 4880, 14840, 500, 7320, 14880, 3200, m_glass, "RV_Glass")
  draw_box(entities, 4880, 12780, 3200, 7320, 14880, 3300, m_glass, "RV_Glass")
  
  # Bronze framing lines and heavy flashings
  draw_box(entities, 4880, 12780, 3200, 4980, 14880, 3250, m_charcoal_metal, "RV_Doors_Windows")
  draw_box(entities, 7220, 12780, 3200, 7320, 14880, 3250, m_charcoal_metal, "RV_Doors_Windows")
  draw_box(entities, 5980, 12780, 500, 6080, 14880, 3200, m_charcoal_metal, "RV_Doors_Windows")
  draw_box(entities, 6120, 12780, 500, 6220, 14880, 3200, m_charcoal_metal, "RV_Doors_Windows")
  
  # Monsoon safety flashing plates
  draw_box(entities, 4860, 12780, 450, 4890, 14880, 3350, m_charcoal_metal, "RV_Doors_Windows")
  draw_box(entities, 7310, 12780, 450, 7340, 14880, 3350, m_charcoal_metal, "RV_Doors_Windows")
  
  # ----------------------------------------------------
  # STEP 10: INTERNAL WALL PARTITIONS (Z=450 to 3050)
  # ----------------------------------------------------
  draw_box(entities, 2440, 9980 - 50, 450, 4880, 9980 + 50, 3050, m_utility, "RV_Walls")
  draw_box(entities, 2440, 11700 - 50, 450, 4880, 11700 + 50, 3050, m_utility, "RV_Walls")
  draw_box(entities, 2440, 7500 - 50, 450, 4880, 7500 + 50, 3050, m_utility, "RV_Walls")
  
  draw_box(entities, 7320, 11200 - 50, 450, 9760, 11200 + 50, 3050, m_utility, "RV_Walls")
  draw_box(entities, 7320, 8400 - 50, 450, 9760, 8400 + 50, 3050, m_utility, "RV_Walls")
  
  # ----------------------------------------------------
  # STEP 11: TRANQUIL COURTYARD OASIS
  # ----------------------------------------------------
  draw_box(entities, 4880, 4880, 0, 7320, 17080, 100, m_laterite, "RV_Courtyard")
  
  # Plunge pool
  draw_box(entities, 5380, 8000, -1100, 6780, 11000, 50, m_laterite, "RV_Courtyard")
  draw_box(entities, 5430, 8050, 0, 6730, 10950, 20, m_water, "RV_Courtyard")
  
  # Bench
  draw_box(entities, 4980, 5100, 100, 7220, 5500, 450, m_laterite, "RV_Courtyard")
  draw_box(entities, 4980, 5100, 450, 7220, 5500, 500, m_deck, "RV_Courtyard")
  draw_box(entities, 5200, 5150, 500, 7000, 5450, 600, m_canvas, "RV_Courtyard")
  
  # Reflecting water channel
  draw_box(entities, 6000, 11000, 50, 6200, 14000, 80, m_water, "RV_Courtyard")
  
  # Plumeria Tree
  draw_coconut_palm(entities, 6700, 15000, 3800, m_deck, m_grass)
  
  # ----------------------------------------------------
  # STEP 12: ROOF SYSTEM WITH DEEP CANOPY OVERHANGS (Z=3350 to 3650)
  # ----------------------------------------------------
  draw_box(entities, -1000, -1000, 3350, 13200, 5880, 3600, m_roof, "RV_Roof")
  draw_box(entities, -1000, -1000, 3350, 13200, -970, 3600, m_utility, "RV_Roof")
  
  draw_box(entities, -1000, 5880, 3350, 5880, 18080, 3600, m_roof, "RV_Roof")
  draw_box(entities, -1000, 18050, 3350, 5880, 18080, 3600, m_utility, "RV_Roof")
  
  draw_box(entities, 6320, 5880, 3350, 13200, 18080, 3600, m_roof, "RV_Roof")
  draw_box(entities, 6320, 18050, 3350, 13200, 18080, 3600, m_utility, "RV_Roof")
  
  draw_box(entities, 12700, 5880, 3350, 17140, 13980, 3550, m_roof, "RV_Roof")
  
  # 6 solar panels
  6.times do |i|
    sy = 6000 + i * 1800
    draw_box(entities, 600, sy, 3600, 700, sy + 1500, 3615, m_charcoal_metal, "RV_Roof")
    draw_box(entities, 1800, sy, 3600, 1900, sy + 1500, 3615, m_charcoal_metal, "RV_Roof")
    
    group = entities.add_group
    ge = group.entities
    p1 = [450, sy - 50, 3630]
    p2 = [2050, sy - 50, 3630]
    p3 = [2050, sy + 1550, 3660]
    p4 = [450, sy + 1550, 3660]
    face = ge.add_face(p1, p2, p3, p4)
    face.pushpull(30) if face
    if m_solar
      ge.each do |e|
        if e.is_a?(Sketchup::Face)
          e.material = m_solar
          e.back_material = m_solar
        end
      end
      group.material = m_solar
    end
    tag = Sketchup.active_model.layers["RV_Roof"]
    group.layer = tag if tag
  end
  
  # Continuous drip edges
  draw_box(entities, -1020, -1020, 3320, 13220, -980, 3350, m_utility, "RV_Roof")
  draw_box(entities, -1020, 5880, -980, 18080, 3320, 3350, m_utility, "RV_Roof")
  draw_box(entities, 13180, 5880, 13220, 18080, 3320, 3350, m_utility, "RV_Roof")
  
  # Gutters and downpipes
  draw_box(entities, 5080, 4980, 3320, 7120, 5080, 3350, m_charcoal_metal, "RV_Roof")
  draw_box(entities, 5080, 5080, 3320, 5180, 17080, 3350, m_charcoal_metal, "RV_Roof")
  draw_box(entities, 7020, 5080, 3320, 7120, 17080, 3350, m_charcoal_metal, "RV_Roof")
  
  draw_box(entities, 4800, 12780, 3300, 4880, 14880, 3350, m_charcoal_metal, "RV_Roof")
  draw_box(entities, 7320, 12780, 3300, 7400, 14880, 3350, m_charcoal_metal, "RV_Roof")
  
  draw_cylinder(entities, 5130, 5030, 450, 3320, 40, m_charcoal_metal, "RV_Roof")
  draw_cylinder(entities, 7070, 5030, 450, 3320, 40, m_charcoal_metal, "RV_Roof")
  draw_cylinder(entities, 5130, 17030, 450, 3320, 40, m_charcoal_metal, "RV_Roof")
  draw_cylinder(entities, 7070, 17030, 450, 3320, 40, m_charcoal_metal, "RV_Roof")
  
  # ----------------------------------------------------
  # STEP 13: FURNITURE DETAILS
  # ----------------------------------------------------
  # Living Area (C1)
  draw_box(entities, 7500, 400, 550, 9600, 1200, 950, m_floor_wood, "RV_Furniture")
  draw_box(entities, 7600, 500, 650, 9500, 1100, 800, m_canvas, "RV_Furniture")
  draw_box(entities, 7800, 1500, 550, 9300, 2100, 800, m_floor_wood, "RV_Furniture")
  
  # TV backdrop wood wall
  draw_box(entities, 11900, 400, 550, 12000, 2200, 3200, m_floor_wood, "RV_Furniture")
  18.times do |i|
    sy = 400 + i * 100
    draw_box(entities, 11870, sy, 550, 11900, sy + 40, 3200, m_utility, "RV_Furniture")
  end
  draw_box(entities, 11840, 1000, 1200, 11870, 1600, 2000, m_utility, "RV_Furniture")
  
  # Dining table (C2)
  draw_box(entities, 1800, 2900, 550, 4200, 3900, 1200, m_floor_wood, "RV_Furniture")
  6.times do |i|
    cx = 2000 + (i % 3) * 1000
    cy = i < 3 ? 2500 : 4300
    draw_box(entities, cx, cy, 550, cx + 500, cy + 500, 900, m_utility, "RV_Furniture")
    draw_box(entities, cx + 20, cy + 20, 900, cx + 480, cy + 480, 950, m_canvas, "RV_Furniture")
  end
  draw_cylinder(entities, 3000, 3400, 1500, 3200, 150, m_charcoal_metal, "RV_Furniture")
  draw_cylinder(entities, 3000, 3400, 3200, 3350, 10, m_charcoal_metal, "RV_Furniture")
  
  # Kitchen Island (C2)
  draw_box(entities, 6000, 4280, 550, 12000, 4880, 1400, m_utility, "RV_Utilities")
  draw_box(entities, 11400, 2440, 550, 12000, 4280, 1400, m_utility, "RV_Utilities")
  draw_box(entities, 7500, 3000, 550, 10200, 3800, 1400, m_floor_wood, "RV_Utilities")
  
  # Master Bed (C3)
  draw_box(entities, 300, 5200, 550, 2100, 7200, 1000, m_floor_wood, "RV_Furniture")
  draw_box(entities, 400, 5300, 650, 2000, 7100, 1050, m_canvas, "RV_Furniture")
  draw_box(entities, 50, 4950, 550, 550, 5450, 900, m_floor_wood, "RV_Furniture")
  draw_box(entities, 1850, 4950, 550, 2350, 5450, 900, m_floor_wood, "RV_Furniture")
  
  # Bed 2 (C5)
  draw_box(entities, 10100, 14600, 550, 11900, 16600, 1000, m_floor_wood, "RV_Furniture")
  draw_box(entities, 10200, 14700, 650, 11800, 16500, 1050, m_canvas, "RV_Furniture")
  
  # Study desk (C6)
  draw_box(entities, 7500, 9000, 550, 9500, 9600, 1200, m_floor_wood, "RV_Furniture")
  draw_box(entities, 8200, 9700, 550, 8700, 10200, 900, m_utility, "RV_Furniture")
  
  # Master vanity (C4)
  draw_box(entities, 2500, 10200, 550, 3000, 11200, 1300, m_utility, "RV_Utilities")
  draw_box(entities, 4200, 10400, 550, 4700, 10900, 900, m_utility, "RV_Utilities")
  draw_box(entities, 3500, 12000, 550, 3520, 13500, 2400, m_glass, "RV_Glass")
  
  # ----------------------------------------------------
  # STEP 14: HIGH-FIDELITY TROPICAL VEGETATION
  # ----------------------------------------------------
  # Left Boundary Forest Line
  draw_coconut_palm(entities, -18000, -15000, 13000, m_deck, m_shrubs)
  draw_coconut_palm(entities, -22000, -5000, 11000, m_deck, m_shrubs)
  draw_jungle_tree(entities, -21000, 2000, 14000, m_deck, m_shrubs)
  draw_coconut_palm(entities, -20000, 9000, 12000, m_deck, m_shrubs)
  draw_jungle_tree(entities, -23000, 17000, 15000, m_deck, m_shrubs)
  draw_coconut_palm(entities, -18000, 25000, 10000, m_deck, m_shrubs)
  
  # Right Boundary Forest Line
  draw_coconut_palm(entities, 28000, -15000, 11500, m_deck, m_shrubs)
  draw_jungle_tree(entities, 29000, -8000, 13500, m_deck, m_shrubs)
  draw_coconut_palm(entities, 32000, -2000, 13000, m_deck, m_shrubs)
  draw_jungle_tree(entities, 30000, 5000, 15000, m_deck, m_shrubs)
  draw_coconut_palm(entities, 34000, 15000, 12000, m_deck, m_shrubs)
  draw_jungle_tree(entities, 28000, 23000, 14000, m_deck, m_shrubs)
  
  # North perimeter forest buffer
  draw_jungle_tree(entities, -25000, 31000, 16000, m_deck, m_shrubs)
  draw_jungle_tree(entities, -15000, 32000, 15000, m_deck, m_shrubs)
  draw_jungle_tree(entities, -5000, 33000, 14000, m_deck, m_shrubs)
  draw_jungle_tree(entities, 5000, 34000, 15500, m_deck, m_shrubs)
  draw_jungle_tree(entities, 15000, 32000, 16000, m_deck, m_shrubs)
  draw_jungle_tree(entities, 25000, 31000, 15000, m_deck, m_shrubs)
  
  # Bamboo clusters at corners
  draw_bamboo_cluster(entities, -18000, -22000, 8, m_grass)
  draw_bamboo_cluster(entities, 22000, -22000, 8, m_grass)
  draw_bamboo_cluster(entities, -10000, 28000, 6, m_grass)
  draw_bamboo_cluster(entities, 10000, 28000, 6, m_grass)
  
  # Rock clusters
  draw_rock_cluster(entities, 7500, -18000, 5, m_laterite)
  draw_rock_cluster(entities, -12000, 22000, 4, m_laterite)
  
  # ----------------------------------------------------
  # STEP 15: PURGE UNUSED MATERIALS/DEFINITIONS FOR LUMION
  # ----------------------------------------------------
  model.definitions.purge_unused
  model.materials.purge_unused
  
  # ----------------------------------------------------
  # STEP 16: CREATE SCENES FOR LUMION CAMERA REFERENCE
  # ----------------------------------------------------
  pages = model.pages
  while pages.count > 0
    pages.erase(pages[0])
  end
  
  def setup_scene(name, eye_coords, target_coords, perspective = true, height = nil)
    model = Sketchup.active_model
    view = model.active_view
    camera = view.camera
    
    camera.perspective = perspective
    if height && !perspective
      camera.height = height
    end
    
    eye = Geom::Point3d.new(eye_coords[0], eye_coords[1], eye_coords[2])
    target = Geom::Point3d.new(target_coords[0], target_coords[1], target_coords[2])
    
    dx = (target.x - eye.x).abs
    dy = (target.y - eye.y).abs
    if dx < 1 && dy < 1
      up = Geom::Vector3d.new(0, 1, 0)
    else
      up = Geom::Vector3d.new(0, 0, 1)
    end
    
    camera.set(eye, target, up)
    
    page = model.pages.add(name)
    page.update(1) # camera flag
    page
  end
  
  # Setup the exact 8 camera views requested for the Lumion rendering workflow
  setup_scene("01 Website Hero Wide View", [48000, -25000, 18000], [6100, 8540, 1200], true)
  setup_scene("02 Front Arrival View", [6100, -12000, 2000], [6100, 2000, 1800], true)
  setup_scene("03 Aerial Estate View", [35000, -18000, 20000], [6100, 8540, 1500], true)
  setup_scene("04 Courtyard Lifestyle View", [6100, 5000, 1600], [6100, 12000, 2200], true)
  setup_scene("05 Deck + Forest View", [6100, -9000, 1500], [6100, 2000, 2200], true)
  setup_scene("06 Roof Solar + Eco Systems View", [-10000, 22000, 15000], [6100, 8540, 3000], true)
  setup_scene("07 Night Luxury View", [22000, -10000, 6000], [6100, 8540, 1500], true)
  setup_scene("08 Brochure Cover View", [6100, -14000, 3000], [6100, 1000, 1500], true)
  
  # ----------------------------------------------------
  # STEP 17: EXPORT COMPLETED LUMION-READY PACKAGE
  # ----------------------------------------------------
  output_dir = "C:/Users/INTEL/Desktop/GOA/WEBSITE/Model/Layout/Lumion_Export_Package"
  Dir.mkdir(output_dir) unless Dir.exist?(output_dir)
  
  lumion_skp_path = File.join(output_dir, "Reserva_Varde_2BHK_Lumion_Ready.skp")
  status_skp = model.save(lumion_skp_path)
  puts "Lumion-Ready Model SKP saved successfully: #{status_skp} at #{lumion_skp_path}"
  
  lumion_dae_path = File.join(output_dir, "Reserva_Varde_2BHK_Lumion_Export.dae")
  status_dae = model.export(lumion_dae_path)
  puts "Lumion Collada DAE exported successfully: #{status_dae} at #{lumion_dae_path}"
  
  # Write a local ruby error check confirmation
  File.write(File.join(output_dir, "ruby_compile_success.log"), "Success! Lumion-Ready SketchUp and Collada DAE files generated cleanly.")
end

begin
  generate_lumion_ready_model
rescue => e
  File.write("C:/Users/INTEL/Desktop/GOA/WEBSITE/Model/Layout/ruby_error_lumion.log", "#{e.class}: #{e.message}\n#{e.backtrace.join("\n")}")
ensure
  Sketchup.quit
end
