# SketchUp Upgraded Ruby Generator for Reserve Varde / Reserva Verde Goa
# 2BHK Compact Modular Eco Estate Upgraded Model
# Autogenerated script — May 2026

require 'sketchup.rb'

def generate_upgraded_model
  model = Sketchup.active_model
  entities = model.entities
  
  # Clear existing entities in the model
  entities.clear!
  
  # ----------------------------------------------------
  # STEP 1: SET UNITS AND OPTIONS
  # ----------------------------------------------------
  model.options['UnitsOptions']['LengthUnit'] = 2 # 2 = Millimeters
  model.options['UnitsOptions']['LengthFormat'] = 0 # Decimal
  model.options['UnitsOptions']['LengthPrecision'] = 0
  
  # Disable scene transitions for fast image export
  model.options['PageOptions']['ShowTransition'] = false
  model.options['PageOptions']['TransitionTime'] = 0.0
  
  # ----------------------------------------------------
  # STEP 2: CREATE TAGS (LAYERS)
  # ----------------------------------------------------
  layers = model.layers
  tags = [
    "CAD Reference",
    "Container Modules",
    "Walls",
    "Glass",
    "Doors Windows",
    "Roof",
    "Deck",
    "Courtyard",
    "Landscape",
    "Furniture",
    "Utilities",
    "Plantation",
    "Lighting"
  ]
  tags.each { |t| layers.add(t) }
  
  # ----------------------------------------------------
  # STEP 3: CREATE MATERIALS
  # ----------------------------------------------------
  materials = model.materials
  
  def add_material(materials, name, r, g, b, alpha = 1.0)
    mat = materials[name] || materials.add(name)
    mat.color = Sketchup::Color.new(r, g, b)
    mat.alpha = alpha
    mat
  end
  
  m_green_metal = add_material(materials, "Deep Forest Green Metal", 26, 47, 37)
  m_bamboo      = add_material(materials, "Bamboo Cladding", 210, 180, 140)
  m_timber      = add_material(materials, "Natural Timber", 138, 90, 56)
  m_charred     = add_material(materials, "Charred Timber", 31, 26, 20)
  m_laterite    = add_material(materials, "Laterite Stone", 140, 91, 63)
  m_plaster     = add_material(materials, "Ivory Lime Plaster", 242, 237, 226)
  m_roof        = add_material(materials, "Dark Standing Seam Roof", 46, 46, 46)
  m_glass       = add_material(materials, "Glass", 184, 220, 230, 0.35)
  m_floor       = add_material(materials, "Warm Wood Flooring", 184, 152, 112)
  m_paving      = add_material(materials, "Natural Stone Paving", 169, 169, 169)
  m_gravel      = add_material(materials, "Gravel", 230, 226, 211)
  m_site_green  = add_material(materials, "Plantation Green", 46, 139, 87)
  m_bronze      = add_material(materials, "Bronze Frame", 58, 51, 40)
  m_water       = add_material(materials, "Water", 173, 216, 230, 0.6)
  m_solar       = add_material(materials, "Solar Cell Panel", 10, 30, 60)
  
  # Helper to draw a box
  def draw_box(entities, x1, y1, z1, x2, y2, z2, material = nil, tag_name = nil)
    group = entities.add_group
    face = group.entities.add_face([x1, y1, z1], [x2, y1, z1], [x2, y2, z1], [x1, y2, z1])
    h = (z2 - z1).to_f
    face.pushpull(h) if h.abs > 0.01
    
    if material
      group.entities.each do |e|
        if e.is_a?(Sketchup::Face)
          e.material = material
          e.back_material = material
        end
      end
      group.material = material
    end
    
    if tag_name
      tag = Sketchup.active_model.layers[tag_name]
      group.layer = tag if tag
    end
    
    group
  end
  
  # Helper to draw a cylinder (for downpipes or poles)
  def draw_cylinder(entities, x, y, z_bottom, z_top, r, material = nil, tag_name = nil)
    group = entities.add_group
    ge = group.entities
    # Create circle
    circle = ge.add_circle([x, y, z_bottom], [0, 0, 1], r, 12)
    face = ge.add_face(circle)
    h = (z_top - z_bottom).to_f
    face.pushpull(h) if h.abs > 0.01
    
    if material
      group.entities.each do |e|
        if e.is_a?(Sketchup::Face)
          e.material = material
          e.back_material = material
        end
      end
      group.material = material
    end
    
    if tag_name
      tag = Sketchup.active_model.layers[tag_name]
      group.layer = tag if tag
    end
    
    group
  end
  
  # Helper to draw vertical privacy screens
  def draw_privacy_screen(entities, x1, y1, x2, y2, z_bottom, z_top, slat_w, slat_d, spacing, material)
    dx = x2 - x1
    dy = y2 - y1
    length = Math.sqrt(dx*dx + dy*dy)
    return if length == 0
    
    num_slats = (length / spacing).floor
    ux = dx / length
    uy = dy / length
    
    num_slats.times do |i|
      sx = x1 + i * spacing * ux
      sy = y1 + i * spacing * uy
      draw_box(entities, sx - slat_w/2.0, sy - slat_d/2.0, z_bottom, sx + slat_w/2.0, sy + slat_d/2.0, z_top, material, "Walls")
    end
  end
  
  # Helper to draw glass railings
  def draw_glass_railing(entities, x1, y1, x2, y2, z, material_post, material_glass)
    dx = x2 - x1
    dy = y2 - y1
    length = Math.sqrt(dx*dx + dy*dy)
    return if length == 0
    
    ux = dx / length
    uy = dy / length
    
    post_spacing = 1500.0
    num_posts = (length / post_spacing).floor + 1
    
    num_posts.times do |i|
      px = x1 + i * post_spacing * ux
      py = y1 + i * post_spacing * uy
      draw_box(entities, px - 25, py - 25, z, px + 25, py + 25, z + 1000, material_post, "Deck")
      
      if i < num_posts - 1
        next_px = x1 + (i + 1) * post_spacing * ux
        next_py = y1 + (i + 1) * post_spacing * uy
        
        # Perpendicular vector to create thickness
        vx = -uy
        vy = ux
        t = 6.0 # half thickness (12mm total)
        
        # Draw a solid glass box
        group = entities.add_group
        ge = group.entities
        
        # Bottom face points of the glass panel
        p1 = [px + 25*ux - t*vx, py + 25*uy - t*vy, z + 50]
        p2 = [next_px - 25*ux - t*vx, next_py - 25*uy - t*vy, z + 50]
        p3 = [next_px - 25*ux + t*vx, next_py - 25*uy + t*vy, z + 50]
        p4 = [px + 25*ux + t*vx, py + 25*uy + t*vy, z + 50]
        
        face = ge.add_face(p1, p2, p3, p4)
        face.pushpull(900) # glass panel height = 900mm (Z goes from 50 to 950)
        
        if material_glass
          ge.each do |e|
            if e.is_a?(Sketchup::Face)
              e.material = material_glass
              e.back_material = material_glass
            end
          end
          group.material = material_glass
        end
        
        tag = Sketchup.active_model.layers["Glass"]
        group.layer = tag if tag
      end
    end
  end
  
  # Helper to draw stylized coconut palm trees
  def draw_coconut_palm(entities, x, y, h_total, material_trunk, material_frond)
    palm_group = entities.add_group
    palm_group.name = "Coconut Palm"
    pe = palm_group.entities
    
    curr_x = x
    curr_y = y
    h = 0
    segs = 10
    seg_h = h_total / segs.to_f
    segs.times do |i|
      next_x = curr_x + i * 20
      next_y = curr_y + i * 40
      draw_box(pe, curr_x - 120, curr_y - 120, h, next_x + 120, next_y + 120, h + seg_h, material_trunk, "Plantation")
      curr_x = next_x
      curr_y = next_y
      h += seg_h
    end
    
    num_fronds = 12
    num_fronds.times do |j|
      angle = j * 2.0 * Math::PI / num_fronds
      fx = curr_x + Math.cos(angle) * 2500
      fy = curr_y + Math.sin(angle) * 2500
      
      # Perpendicular vector in the XY plane
      vx = -Math.sin(angle)
      vy = Math.cos(angle)
      w = 120.0 # half width of the frond
      
      # Draw frond as a 3D box
      frond_group = pe.add_group
      fe = frond_group.entities
      
      p1 = [curr_x - w*vx, curr_y - w*vy, h - 400]
      p2 = [fx - w*vx, fy - w*vy, h]
      p3 = [fx + w*vx, fy + w*vy, h]
      p4 = [curr_x + w*vx, curr_y + w*vy, h - 400]
      
      face = fe.add_face(p1, p2, p3, p4)
      face.pushpull(50) if face # 50mm thickness
      
      if material_frond
        fe.each do |e|
          if e.is_a?(Sketchup::Face)
            e.material = material_frond
            e.back_material = material_frond
          end
        end
        frond_group.material = material_frond
      end
      
      tag = Sketchup.active_model.layers["Plantation"]
      frond_group.layer = tag if tag
    end
    
    tag = Sketchup.active_model.layers["Plantation"]
    palm_group.layer = tag if tag
  end
  
  # Helper to draw bamboo clusters
  def draw_bamboo_cluster(entities, x, y, num_stalks, material_bamboo)
    b_group = entities.add_group
    b_group.name = "Bamboo Cluster"
    be = b_group.entities
    
    num_stalks.times do |i|
      ox = x + rand(1200) - 600
      oy = y + rand(1200) - 600
      h = 5000 + rand(2500)
      draw_box(be, ox - 20, oy - 20, 0, ox + 20, oy + 20, h, material_bamboo, "Plantation")
      draw_box(be, ox - 800, oy - 800, h - 1500, ox + 800, oy + 800, h + 300, material_bamboo, "Plantation")
    end
    
    tag = Sketchup.active_model.layers["Plantation"]
    b_group.layer = tag if tag
  end
  
  # Helper to draw a frame and glass for doors/windows
  def draw_opening_frame(entities, x1, y1, x2, y2, z_bottom, z_top, thickness, type)
    frame_thick = 50
    x_min, x_max = [x1, x2].minmax
    y_min, y_max = [y1, y2].minmax
    
    frame_group = entities.add_group
    frame_group.name = type == :door ? "Door Frame" : "Window Frame"
    
    model = Sketchup.active_model
    bronze_mat = model.materials["Bronze Frame"]
    glass_mat = model.materials["Glass"]
    fe = frame_group.entities
    
    if y1 == y2
      y = y1
      # Top/bottom rails
      draw_box(fe, x_min, y - frame_thick/2.0, z_bottom, x_max, y + frame_thick/2.0, z_bottom + frame_thick, bronze_mat, "Doors Windows")
      draw_box(fe, x_min, y - frame_thick/2.0, z_top - frame_thick, x_max, y + frame_thick/2.0, z_top, bronze_mat, "Doors Windows")
      # Left/right stiles
      draw_box(fe, x_min, y - frame_thick/2.0, z_bottom + frame_thick, x_min + frame_thick, y + frame_thick/2.0, z_top - frame_thick, bronze_mat, "Doors Windows")
      draw_box(fe, x_max - frame_thick, y - frame_thick/2.0, z_bottom + frame_thick, x_max, y + frame_thick/2.0, z_top - frame_thick, bronze_mat, "Doors Windows")
      
      if type == :window
        draw_box(fe, x_min + frame_thick, y - 5, z_bottom + frame_thick, x_max - frame_thick, y + 5, z_top - frame_thick, glass_mat, "Glass")
      else
        if x_max - x_min > 1500
          mid_x = (x_min + x_max)/2.0
          draw_box(fe, x_min + frame_thick, y - 10, z_bottom + frame_thick, mid_x, y + 10, z_top - frame_thick, glass_mat, "Glass")
          draw_box(fe, mid_x, y - 20, z_bottom + frame_thick, x_max - frame_thick, y, z_top - frame_thick, glass_mat, "Glass")
        else
          timber_mat = model.materials["Natural Timber"]
          draw_box(fe, x_min + frame_thick + 10, y - 20, z_bottom + frame_thick, x_max - frame_thick - 10, y + 20, z_top - frame_thick, timber_mat, "Doors Windows")
        end
      end
    else
      x = x1
      # Top/bottom rails
      draw_box(fe, x - frame_thick/2.0, y_min, z_bottom, x + frame_thick/2.0, y_max, z_bottom + frame_thick, bronze_mat, "Doors Windows")
      draw_box(fe, x - frame_thick/2.0, y_min, z_top - frame_thick, x + frame_thick/2.0, y_max, z_top, bronze_mat, "Doors Windows")
      # Left/right stiles
      draw_box(fe, x - frame_thick/2.0, y_min, z_bottom + frame_thick, x + frame_thick/2.0, y_min + frame_thick, z_top - frame_thick, bronze_mat, "Doors Windows")
      draw_box(fe, x - frame_thick/2.0, y_max - frame_thick, z_bottom + frame_thick, x + frame_thick/2.0, y_max, z_top - frame_thick, bronze_mat, "Doors Windows")
      
      if type == :window
        draw_box(fe, x - 5, y_min + frame_thick, z_bottom + frame_thick, x + 5, y_max - frame_thick, z_top - frame_thick, glass_mat, "Glass")
      else
        if y_max - y_min > 1500
          mid_y = (y_min + y_max)/2.0
          draw_box(fe, x - 10, y_min + frame_thick, z_bottom + frame_thick, x + 10, mid_y, z_top - frame_thick, glass_mat, "Glass")
          draw_box(fe, x - 20, mid_y, z_bottom + frame_thick, x, y_max - frame_thick, z_top - frame_thick, glass_mat, "Glass")
        else
          timber_mat = model.materials["Natural Timber"]
          draw_box(fe, x - 20, y_min + frame_thick + 10, z_bottom + frame_thick, x + 20, y_max - frame_thick - 10, z_top - frame_thick, timber_mat, "Doors Windows")
        end
      end
    end
    
    tag = model.layers["Doors Windows"]
    frame_group.layer = tag if tag
    frame_group
  end
  
  # Wall drawer with openings
  def draw_wall_with_openings(entities, x1, y1, x2, y2, z_bottom, z_top, thickness, material_ext, material_int, openings = [])
    if y1 == y2
      y = y1
      x_min, x_max = [x1, x2].minmax
      current_x = x_min
      
      sorted_openings = openings.sort_by { |o| o[:start] }
      sorted_openings.each do |op|
        op_start = x_min + op[:start]
        op_end = op_start + op[:width]
        
        if op_start > current_x
          draw_box(entities, current_x, y - thickness/2.0, z_bottom, op_start, y + thickness/2.0, z_top, material_ext, "Walls")
        end
        
        if op[:type] == :window && op[:sill] > 0
          draw_box(entities, op_start, y - thickness/2.0, z_bottom, op_end, y + thickness/2.0, z_bottom + op[:sill], material_ext, "Walls")
        end
        
        op_top = z_bottom + op[:sill] + op[:height]
        if op_top < z_top
          draw_box(entities, op_start, y - thickness/2.0, op_top, op_end, y + thickness/2.0, z_top, material_ext, "Walls")
        end
        
        draw_opening_frame(entities, op_start, y, op_end, y, z_bottom + op[:sill], z_bottom + op[:sill] + op[:height], thickness, op[:type])
        current_x = op_end
      end
      
      if x_max > current_x
        draw_box(entities, current_x, y - thickness/2.0, z_bottom, x_max, y + thickness/2.0, z_top, material_ext, "Walls")
      end
      
    elsif x1 == x2
      x = x1
      y_min, y_max = [y1, y2].minmax
      current_y = y_min
      
      sorted_openings = openings.sort_by { |o| o[:start] }
      sorted_openings.each do |op|
        op_start = y_min + op[:start]
        op_end = op_start + op[:width]
        
        if op_start > current_y
          draw_box(entities, x - thickness/2.0, current_y, z_bottom, x + thickness/2.0, op_start, z_top, material_ext, "Walls")
        end
        
        if op[:type] == :window && op[:sill] > 0
          draw_box(entities, x - thickness/2.0, op_start, z_bottom, x + thickness/2.0, op_end, z_bottom + op[:sill], material_ext, "Walls")
        end
        
        op_top = z_bottom + op[:sill] + op[:height]
        if op_top < z_top
          draw_box(entities, x - thickness/2.0, op_start, op_top, x + thickness/2.0, op_end, z_top, material_ext, "Walls")
        end
        
        draw_opening_frame(entities, x, op_start, x, op_end, z_bottom + op[:sill], z_bottom + op[:sill] + op[:height], thickness, op[:type])
        current_y = op_end
      end
      
      if y_max > current_y
        draw_box(entities, x - thickness/2.0, current_y, z_bottom, x + thickness/2.0, y_max, z_top, material_ext, "Walls")
      end
    end
  end
  
  # ----------------------------------------------------
  # STEP 4: DRAW 1-ACRE SITE CONTEXT
  # ----------------------------------------------------
  plot_w = 63600
  x_min = 6100 - plot_w/2.0
  x_max = 6100 + plot_w/2.0
  y_min = 8540 - plot_w/2.0
  y_max = 8540 + plot_w/2.0
  
  # Lawn Base
  draw_box(entities, x_min, y_min, -100, x_max, y_max, 0, m_site_green, "Landscape")
  
  # Winding Gravel Driveway
  draw_box(entities, 11000, -23260, 0, 16000, -8000, 10, m_gravel, "Landscape")
  # Parking court for 2 cars
  draw_box(entities, 11000, -8000, 0, 18000, -2400, 10, m_gravel, "Landscape")
  
  # Winding Laterite Stone Pathways linking driveway, villa, and meditation area
  draw_box(entities, 14000, -2400, 0, 14800, 6880, 20, m_paving, "Landscape") # pathway to C7 / courtyard
  draw_box(entities, 3000, -2400, 0, 3800, 0, 20, m_paving, "Landscape") # main pathway from parking court to verandah
  
  # Heavy stone entry piers & Gate
  draw_box(entities, 11000, -22000, 0, 11800, -21200, 2400, m_laterite, "Landscape") # Left pier
  draw_box(entities, 15200, -22000, 0, 16000, -21200, 2400, m_laterite, "Landscape") # Right pier
  draw_box(entities, 11800, -21700, 100, 14800, -21600, 1800, m_timber, "Landscape")  # Gate (partially open)
  
  # Firepit/Meditation zone (X=-15000, Y=25000)
  draw_box(entities, -17000, 23000, 0, -13000, 27000, 20, m_paving, "Landscape") # Paved circle base
  # Fire ring (laterite stone box with hollow top modeled simple)
  draw_box(entities, -15400, 24600, 20, -14600, 25400, 300, m_laterite, "Landscape")
  draw_box(entities, -15250, 24750, 50, -14750, 25250, 320, m_charred, "Landscape") # inside fire pit
  # 4 seating logs around firepit
  draw_box(entities, -16500, 24800, 20, -16000, 25200, 450, m_timber, "Landscape")
  draw_box(entities, -14000, 24800, 20, -13500, 25200, 450, m_timber, "Landscape")
  draw_box(entities, -15200, 26000, 20, -14800, 26500, 450, m_timber, "Landscape")
  draw_box(entities, -15200, 23500, 20, -14800, 24000, 450, m_timber, "Landscape")
  
  # Winding stepping stones to firepit
  12.times do |i|
    sx = -1000 - i * 1100
    sy = 12000 + i * 1000
    draw_box(entities, sx - 300, sy - 300, 10, sx + 300, sy + 300, 30, m_paving, "Landscape")
  end
  
  # Labeled Landscaped Utility & Service Zone (conforms to monsoon & MEP decisions)
  # Decentralized STP / Bio-digester box
  draw_box(entities, 14000, 3500, 0, 15500, 5000, 1100, m_charred, "Utilities")
  draw_box(entities, 14050, 3550, 1100, 15450, 4950, 1150, m_bronze, "Utilities") # service lids
  
  # Rainwater Harvesting & Filtration Tank
  draw_cylinder(entities, 14800, 6500, 0, 1800, 900, m_charred, "Utilities") # Tank cylinder
  draw_cylinder(entities, 14800, 6500, 1800, 1900, 920, m_bronze, "Utilities") # Tank lid
  
  # Greywater Collection & Reuse Box
  draw_box(entities, 14000, 5500, 0, 15200, 7000, 800, m_charred, "Utilities")
  draw_box(entities, 14050, 5550, 800, 15150, 6950, 840, m_bronze, "Utilities")
  
  # Decorative Timber Slat Privacy Screen (concealing utilities from main approach)
  draw_privacy_screen(entities, 13500, 3000, 13500, 7500, 0, 2200, 40, 60, 200, m_timber)
  
  # Large primary rainwater tank at the rear
  draw_box(entities, 14000, 14000, 0, 16000, 16000, 1200, m_roof, "Utilities") # Base
  draw_cylinder(entities, 15000, 15000, 0, 2400, 1200, m_charred, "Utilities") # Main cistern
  
  # Future expansion zone pad
  draw_box(entities, -20000, 10000, 0, -10000, 20000, 10, m_site_green, "Utilities")
  
  # ----------------------------------------------------
  # STEP 5: DRAW LATERITE STONE PLINTHS (Z=0 to 450)
  # ----------------------------------------------------
  draw_box(entities, 0, 0, 0, 12200, 4880, 450, m_laterite, "Landscape") # South
  draw_box(entities, 0, 4880, 0, 4880, 17080, 450, m_laterite, "Landscape") # West
  draw_box(entities, 7320, 4880, 0, 12200, 17080, 450, m_laterite, "Landscape") # East
  draw_box(entities, 13700, 6880, 0, 16140, 12980, 450, m_laterite, "Landscape") # C7
  
  # ----------------------------------------------------
  # STEP 6: UPGRADED TIMBER DECKS
  # ----------------------------------------------------
  # South Verandah
  draw_box(entities, -1500, -2400, 0, 13700, 0, 400, m_timber, "Deck")
  
  # Pergola structure over South Verandah
  # Columns
  draw_box(entities, -1450, -2350, 400, -1350, -2250, 3200, m_timber, "Deck")
  draw_box(entities, 3000, -2350, 400, 3100, -2250, 3200, m_timber, "Deck")
  draw_box(entities, 8000, -2350, 400, 8100, -2250, 3200, m_timber, "Deck")
  draw_box(entities, 13550, -2350, 400, 13650, -2250, 3200, m_timber, "Deck")
  # Cross beams
  draw_box(entities, -1500, -2400, 3100, 13700, -2200, 3200, m_timber, "Deck")
  
  # Forest Deck
  draw_box(entities, 0, -6400, 0, 12200, -2400, 200, m_timber, "Deck")
  # Glass safety railing on the forest deck edge
  draw_glass_railing(entities, 0, -6350, 12200, -6350, 200, m_bronze, m_glass)
  
  # Outdoor Sun Loungers on forest deck
  draw_box(entities, 2000, -5000, 200, 2700, -3100, 500, m_timber, "Furniture") # frame 1
  draw_box(entities, 2100, -4900, 500, 2600, -3200, 600, m_plaster, "Furniture") # cushion 1
  draw_box(entities, 3500, -5000, 200, 4200, -3100, 500, m_timber, "Furniture") # frame 2
  draw_box(entities, 3600, -4900, 500, 4100, -3200, 600, m_plaster, "Furniture") # cushion 2
  
  # Outdoor dining table on forest deck
  draw_box(entities, 7000, -5000, 200, 9200, -4000, 950, m_timber, "Furniture")
  # 6 benches / chairs
  6.times do |i|
    cx = 7200 + (i % 3) * 750
    cy = i < 3 ? -5400 : -3700
    draw_box(entities, cx, cy, 200, cx + 450, cy + 450, 650, m_charred, "Furniture")
  end
  
  # ----------------------------------------------------
  # STEP 7: BUILD CONTAINER SHELLS (C1 to C7)
  # ----------------------------------------------------
  def draw_container_shell(entities, x_sw, y_sw, length, width, height, m_metal, m_wood, tag_name, name)
    c_group = entities.add_group
    c_group.name = name
    ce = c_group.entities
    
    # floor slab
    draw_box(ce, x_sw, y_sw, 450, x_sw + length, y_sw + width, 550, m_wood, tag_name)
    # roof slab
    draw_box(ce, x_sw, y_sw, 450 + height - 150, x_sw + length, y_sw + width, 450 + height, m_metal, tag_name)
    # 4 corner columns
    cw = 150
    draw_box(ce, x_sw, y_sw, 550, x_sw + cw, y_sw + cw, 450 + height - 150, m_metal, tag_name)
    draw_box(ce, x_sw + length - cw, y_sw, 550, x_sw + length, y_sw + cw, 450 + height - 150, m_metal, tag_name)
    draw_box(ce, x_sw, y_sw + width - cw, 550, x_sw + cw, y_sw + width, 450 + height - 150, m_metal, tag_name)
    draw_box(ce, x_sw + length - cw, y_sw + width - cw, 550, x_sw + length, y_sw + width, 450 + height - 150, m_metal, tag_name)
    
    tag = Sketchup.active_model.layers[tag_name]
    c_group.layer = tag if tag
    c_group
  end
  
  draw_container_shell(entities, 0, 0, 12200, 2440, 2900, m_green_metal, m_floor, "Container Modules", "C1_Living")
  draw_container_shell(entities, 0, 2440, 12200, 2440, 2900, m_green_metal, m_floor, "Container Modules", "C2_Dining_Kitchen")
  draw_container_shell(entities, 0, 4880, 2440, 12200, 2900, m_green_metal, m_floor, "Container Modules", "C3_MasterBR")
  draw_container_shell(entities, 2440, 4880, 2440, 12200, 2900, m_green_metal, m_floor, "Container Modules", "C4_MasterBath")
  draw_container_shell(entities, 9760, 4880, 2440, 12200, 2900, m_green_metal, m_floor, "Container Modules", "C5_BR2")
  draw_container_shell(entities, 7320, 4880, 2440, 12200, 2900, m_green_metal, m_floor, "Container Modules", "C6_BR2Bath")
  draw_container_shell(entities, 13700, 6880, 2440, 6100, 2900, m_green_metal, m_floor, "Container Modules", "C7_Service")
  
  # ----------------------------------------------------
  # STEP 8: BUILD WALLS & OPENINGS
  # ----------------------------------------------------
  # South wall (Y=0)
  # Charred timber feature wall at the entry (from X=0 to X=3500) and Bamboo cladding elsewhere
  openings_south = [
    { start: 1500, width: 1000, sill: 0, height: 2100, type: :door },   # D01 Main Entrance
    { start: 3500, width: 2800, sill: 900, height: 1500, type: :window }, # W08 Foyer Window
    { start: 7500, width: 4200, sill: 0, height: 2400, type: :door }     # D10 Sliding Glass Door
  ]
  draw_wall_with_openings(entities, 0, 0, 3500, 0, 450, 3350, 230, m_charred, m_plaster, [openings_south[0]])
  draw_wall_with_openings(entities, 3500, 0, 12200, 0, 450, 3350, 230, m_bamboo, m_plaster, [openings_south[1], openings_south[2]])
  
  # West outer wall (X=0)
  openings_west = [
    { start: 6000, width: 5400, sill: 900, height: 1500, type: :window }, # W01 Master Suite View
    { start: 14500, width: 1200, sill: 1200, height: 900, type: :window } # W03 bathroom window
  ]
  draw_wall_with_openings(entities, 0, 0, 0, 17080, 450, 3350, 230, m_charred, m_plaster, openings_west)
  
  # Add vertical timber privacy screens in front of large Master Suite window W01 (from Y=6000 to Y=11400, X=-50 to screen it slightly)
  draw_privacy_screen(entities, -100, 6000, -100, 11400, 550, 3200, 40, 60, 250, m_timber)
  
  # East outer wall (X=12200)
  openings_east = [
    { start: 13000, width: 2400, sill: 900, height: 1500, type: :window } # W05 BR2 View
  ]
  draw_wall_with_openings(entities, 12200, 0, 12200, 17080, 450, 3350, 230, m_charred, m_plaster, openings_east)
  
  # North outer wall (West wing, Y=17080, X=0 to 4880)
  openings_north_w = [
    { start: 3000, width: 1500, sill: 900, height: 1500, type: :window } # W04 private lounge window
  ]
  draw_wall_with_openings(entities, 0, 17080, 4880, 17080, 450, 3350, 230, m_bamboo, m_plaster, openings_north_w)
  
  # North outer wall (East wing, Y=17080, X=7320 to 12200)
  draw_wall_with_openings(entities, 7320, 17080, 12200, 17080, 450, 3350, 230, m_charred, m_plaster, [])
  
  # Courtyard West Wall (X=4880, Y=4880 to 17080)
  draw_wall_with_openings(entities, 4880, 4880, 4880, 12780, 450, 3350, 150, m_bamboo, m_plaster, [])
  draw_wall_with_openings(entities, 4880, 14880, 4880, 17080, 450, 3350, 150, m_bamboo, m_plaster, [])
  
  # Courtyard East Wall (X=7320, Y=4880 to 17080)
  openings_court_e = [
    { start: 4120, width: 2400, sill: 900, height: 1500, type: :window } # W06 BR2 window
  ]
  draw_wall_with_openings(entities, 7320, 4880, 7320, 12780, 450, 3350, 150, m_bamboo, m_plaster, openings_court_e)
  draw_wall_with_openings(entities, 7320, 14880, 7320, 17080, 450, 3350, 150, m_bamboo, m_plaster, [])
  
  # South side of Courtyard (North wall of C2, Y=4880, X=4880 to 7320)
  openings_court_s = [
    { start: 200, width: 2000, sill: 0, height: 2400, type: :door }
  ]
  draw_wall_with_openings(entities, 4880, 4880, 7320, 4880, 450, 3350, 150, m_bamboo, m_plaster, openings_court_s)
  
  # C7 walls (Detached Utility, X=13700 to 16140, Y=6880 to 12980)
  openings_c7 = [
    { start: 1120, width: 900, sill: 0, height: 2100, type: :door },     # D09 utility service door
    { start: 3120, width: 2000, sill: 900, height: 1500, type: :window }  # W09 utility store window
  ]
  draw_wall_with_openings(entities, 16140, 6880, 16140, 12980, 450, 3350, 230, m_charred, m_plaster, openings_c7) # East
  draw_wall_with_openings(entities, 13700, 6880, 13700, 12980, 450, 3350, 230, m_charred, m_plaster, []) # West
  draw_wall_with_openings(entities, 13700, 6880, 16140, 6880, 450, 3350, 230, m_charred, m_plaster, [])  # South
  draw_wall_with_openings(entities, 13700, 12980, 16140, 12980, 450, 3350, 230, m_charred, m_plaster, []) # North
  
  # ----------------------------------------------------
  # STEP 9: GLASS CONNECTOR CORRIDORS (Z=450 to 3350)
  # ----------------------------------------------------
  # Walkway floor
  draw_box(entities, 4880, 12780, 450, 7320, 14880, 500, m_timber, "Glass")
  # Glass outer walls
  draw_box(entities, 4880, 12780, 500, 7320, 12820, 3200, m_glass, "Glass")
  draw_box(entities, 4880, 14840, 500, 7320, 14880, 3200, m_glass, "Glass")
  # Glass Roof
  draw_box(entities, 4880, 12780, 3200, 7320, 14880, 3300, m_glass, "Glass")
  # Bronze framing lines and vertical metal flashing strips at glass-to-container junctions
  draw_box(entities, 4880, 12780, 3200, 4980, 14880, 3250, m_bronze, "Doors Windows")
  draw_box(entities, 7220, 12780, 3200, 7320, 14880, 3250, m_bronze, "Doors Windows")
  draw_box(entities, 5980, 12780, 500, 6080, 14880, 3200, m_bronze, "Doors Windows")
  draw_box(entities, 6120, 12780, 500, 6220, 14880, 3200, m_bronze, "Doors Windows")
  
  # Metal flashing strips at C4 junction (X=4880) and C6 junction (X=7320) for heavy monsoon protection
  draw_box(entities, 4860, 12780, 450, 4890, 14880, 3350, m_bronze, "Doors Windows")
  draw_box(entities, 7310, 12780, 450, 7340, 14880, 3350, m_bronze, "Doors Windows")
  
  # ----------------------------------------------------
  # STEP 10: INTERNAL PARTITIONS (Z=450 to 3050)
  # ----------------------------------------------------
  # Inside C4 (Master Wing)
  draw_box(entities, 2440, 9980 - 50, 450, 4880, 9980 + 50, 3050, m_plaster, "Walls") # Wardrobe
  draw_box(entities, 2440, 11700 - 50, 450, 4880, 11700 + 50, 3050, m_plaster, "Walls") # Bath
  draw_box(entities, 2440, 7500 - 50, 450, 4880, 7500 + 50, 3050, m_plaster, "Walls") # Lounge
  
  # Inside C6 (Bedroom 2 / Study Wing)
  draw_box(entities, 7320, 11200 - 50, 450, 9760, 11200 + 50, 3050, m_plaster, "Walls") # Bath
  draw_box(entities, 7320, 8400 - 50, 450, 9760, 8400 + 50, 3050, m_plaster, "Walls") # Powder
  
  # ----------------------------------------------------
  # STEP 11: COURTYARD DETAILS (Stone Paving, Pool, Tree, Seating)
  # ----------------------------------------------------
  # Herringbone paved floor
  draw_box(entities, 4880, 4880, 0, 7320, 17080, 100, m_paving, "Courtyard")
  
  # Plunge pool
  draw_box(entities, 5380, 8000, -1100, 6780, 11000, 50, m_laterite, "Courtyard") # pool wall
  draw_box(entities, 5430, 8050, 0, 6730, 10950, 20, m_water, "Courtyard") # water
  
  # Courtyard concrete seating edge with wooden bench on top
  draw_box(entities, 4980, 5100, 100, 7220, 5500, 450, m_laterite, "Courtyard") # base
  draw_box(entities, 4980, 5100, 450, 7220, 5500, 500, m_timber, "Courtyard") # wood bench top
  draw_box(entities, 5200, 5150, 500, 7000, 5450, 600, m_plaster, "Courtyard") # outdoor white cushions
  
  # Central reflecting water channel feeding the pool
  draw_box(entities, 6000, 11000, 50, 6160, 14000, 100, m_water, "Courtyard")
  
  # Feature Plumeria Tree (stylized curved trunk and layered crown)
  draw_coconut_palm(entities, 6700, 15000, 4000, m_timber, m_site_green)
  
  # ----------------------------------------------------
  # STEP 12: ROOF STRUCTURE WITH DEEP OVERHANGS (Z=3350 to 3650)
  # ----------------------------------------------------
  # Deep overhangs of 1000 mm (1.0m) past the container edges
  # Fascia boards in charcoal black around the roof edges
  
  # South Roof (C1 + C2)
  # Container extends from X=0 to 12200, Y=0 to 4880
  # Roof extends X=-1000 to 13200, Y=-1000 to 5880
  draw_box(entities, -1000, -1000, 3350, 13200, 5880, 3600, m_roof, "Roof")
  draw_box(entities, -1000, -1000, 3350, 13200, -970, 3600, m_charred, "Roof") # South fascia
  
  # West Roof (C3 + C4)
  # Container extends X=0 to 4880, Y=4880 to 17080
  # Roof extends X=-1000 to 5880, Y=5880 to 18080
  draw_box(entities, -1000, 5880, 3350, 5880, 18080, 3600, m_roof, "Roof")
  draw_box(entities, -1000, 18050, 3350, 5880, 18080, 3600, m_charred, "Roof") # North fascia
  
  # East Roof (C5 + C6)
  # Container extends X=7320 to 12200, Y=4880 to 17080
  # Roof extends X=6320 to 13200, Y=5880 to 18080
  draw_box(entities, 6320, 5880, 3350, 13200, 18080, 3600, m_roof, "Roof")
  draw_box(entities, 6320, 18050, 3350, 13200, 18080, 3600, m_charred, "Roof") # North fascia
  
  # Detached C7 Utility Roof
  # Container extends X=13700 to 16140, Y=6880 to 12980
  # Roof extends X=12700 to 17140, Y=5880 to 13980
  draw_box(entities, 12700, 5880, 3350, 17140, 13980, 3550, m_roof, "Roof")
  
  # 6 Low-profile Fixed Solar Panels on West Wing (C3/C4 Roof)
  # Low-angle mounting rails and low-profile bracket system (water runoff/monsoon proof)
  6.times do |i|
    sy = 6000 + i * 1800
    # Rails running under the panels (slightly sloped)
    draw_box(entities, 600, sy, 3600, 700, sy + 1500, 3615, m_bronze, "Roof")
    draw_box(entities, 1800, sy, 3600, 1900, sy + 1500, 3615, m_bronze, "Roof")
    
    # Slight tilted solar panel frame
    # Z ranges from 3615 (South) to 3645 (North) for the 3D panel box
    group = entities.add_group
    ge = group.entities
    
    p1 = [450, sy - 50, 3630]
    p2 = [2050, sy - 50, 3630]
    p3 = [2050, sy + 1550, 3660]
    p4 = [450, sy + 1550, 3660]
    
    face = ge.add_face(p1, p2, p3, p4)
    face.pushpull(30) if face
    
    # Apply solar panel texture
    if m_solar
      ge.each do |e|
        if e.is_a?(Sketchup::Face)
          e.material = m_solar
          e.back_material = m_solar
        end
      end
      group.material = m_solar
    end
    
    tag = Sketchup.active_model.layers["Roof"]
    group.layer = tag if tag
  end
  
  # Drip edges on roof canopy lines for monsoon splash protection
  # South Roof drip edge (under overhang, Y = -1000)
  draw_box(entities, -1020, -1020, 3320, 13220, -980, 3350, m_charred, "Roof")
  # West Roof drip edge (under overhang, X = -1000)
  draw_box(entities, -1020, 5880, -980, 18080, 3320, 3350, m_charred, "Roof")
  # East Roof drip edge (under overhang, X = 13200)
  draw_box(entities, 13180, 5880, 13220, 18080, 3320, 3350, m_charred, "Roof")
  
  # Gutter lines and Downpipes
  # Gutters on courtyard edges
  draw_box(entities, 5080, 4980, 3320, 7120, 5080, 3350, m_bronze, "Roof")
  draw_box(entities, 5080, 5080, 3320, 5180, 17080, 3350, m_bronze, "Roof")
  draw_box(entities, 7020, 5080, 3320, 7120, 17080, 3350, m_bronze, "Roof")
  # Concealed gutters along glass corridor roof edges
  draw_box(entities, 4800, 12780, 3300, 4880, 14880, 3350, m_bronze, "Roof")
  draw_box(entities, 7320, 12780, 3300, 7400, 14880, 3350, m_bronze, "Roof")
  # Downpipes (diameter 80 mm) at courtyard corners
  draw_cylinder(entities, 5130, 5030, 450, 3320, 40, m_bronze, "Roof")
  draw_cylinder(entities, 7070, 5030, 450, 3320, 40, m_bronze, "Roof")
  draw_cylinder(entities, 5130, 17030, 450, 3320, 40, m_bronze, "Roof")
  draw_cylinder(entities, 7070, 17030, 450, 3320, 40, m_bronze, "Roof")
  
  # ----------------------------------------------------
  # STEP 13: FURNITURE & INTERIOR DETAILS
  # ----------------------------------------------------
  # Living (C1)
  draw_box(entities, 7500, 400, 550, 9600, 1200, 1000, m_timber, "Furniture") # sofa frame
  draw_box(entities, 7600, 500, 650, 9500, 1100, 800, m_plaster, "Furniture") # cushions
  draw_box(entities, 7800, 1500, 550, 9300, 2100, 850, m_timber, "Furniture") # coffee table
  draw_box(entities, 7300, 300, 550, 9800, 350, 560, m_charred, "Furniture") # area rug
  
  # TV Wall with slatted timber backdrop in Living (C1)
  # Backdrop wall
  draw_box(entities, 11900, 400, 550, 12000, 2200, 3200, m_timber, "Furniture")
  # Slats (every 100 mm)
  18.times do |i|
    sy = 400 + i * 100
    draw_box(entities, 11870, sy, 550, 11900, sy + 40, 3200, m_charred, "Furniture")
  end
  # TV screen (thin black box)
  draw_box(entities, 11840, 1000, 1200, 11870, 1600, 2000, m_charred, "Furniture")
  
  # Dining (C2)
  draw_box(entities, 1800, 2900, 550, 4200, 3900, 1250, m_timber, "Furniture") # Table
  6.times do |i|
    cx = 2000 + (i % 3) * 1000
    cy = i < 3 ? 2500 : 4300
    draw_box(entities, cx, cy, 550, cx + 500, cy + 500, 950, m_charred, "Furniture")
  end
  # Designer pendant light over dining table
  draw_cylinder(entities, 3000, 3400, 1500, 3200, 150, m_bronze, "Furniture") # shade
  draw_cylinder(entities, 3000, 3400, 3200, 3350, 10, m_bronze, "Furniture")  # wire
  
  # Kitchen (C2)
  draw_box(entities, 6000, 4280, 550, 12000, 4880, 1450, m_charred, "Utilities") # Counter
  draw_box(entities, 11400, 2440, 550, 12000, 4280, 1450, m_charred, "Utilities")
  draw_box(entities, 7500, 3000, 550, 10200, 3800, 1450, m_timber, "Utilities") # Island
  
  # Master Bedroom (C3)
  draw_box(entities, 300, 5200, 550, 2100, 7200, 1100, m_timber, "Furniture") # bed frame
  draw_box(entities, 400, 5300, 650, 2000, 7100, 1050, m_plaster, "Furniture") # mattress
  draw_box(entities, 50, 4950, 550, 550, 5450, 950, m_timber, "Furniture")
  draw_box(entities, 1850, 4950, 550, 2350, 5450, 950, m_timber, "Furniture")
  
  # Bedroom 2 (C5)
  draw_box(entities, 10100, 14600, 550, 11900, 16600, 1100, m_timber, "Furniture") # bed frame
  draw_box(entities, 10200, 14700, 650, 11800, 16500, 1050, m_plaster, "Furniture") # mattress
  
  # Study Desk in C6
  draw_box(entities, 7500, 9000, 550, 9500, 9600, 1250, m_timber, "Furniture")
  draw_box(entities, 8200, 9700, 550, 8700, 10200, 950, m_charred, "Furniture")
  
  # Master Vanity & Shower Glass (C4)
  draw_box(entities, 2500, 10200, 550, 3000, 11200, 1350, m_plaster, "Utilities") # Vanity
  draw_box(entities, 4200, 10400, 550, 4700, 10900, 950, m_plaster, "Utilities") # WC
  # Shower partition glass
  draw_box(entities, 3500, 12000, 550, 3520, 13500, 2450, m_glass, "Glass")
  
  # ----------------------------------------------------
  # STEP 14: GOA JUNGLE TROPICAL LANDSCAPING
  # ----------------------------------------------------
  # We will scatter detailed coconut palms and bamboo clusters around the site context
  # Left forest buffer
  draw_coconut_palm(entities, -18000, -15000, 12000, m_timber, m_site_green)
  draw_coconut_palm(entities, -22000, -5000, 11000, m_timber, m_site_green)
  draw_coconut_palm(entities, -20000, 5000, 13000, m_timber, m_site_green)
  draw_coconut_palm(entities, -24000, 15000, 12000, m_timber, m_site_green)
  draw_coconut_palm(entities, -18000, 25000, 10000, m_timber, m_site_green)
  
  # Right forest buffer
  draw_coconut_palm(entities, 28000, -15000, 11000, m_timber, m_site_green)
  draw_coconut_palm(entities, 32000, -5000, 13000, m_timber, m_site_green)
  draw_coconut_palm(entities, 30000, 5000, 12000, m_timber, m_site_green)
  draw_coconut_palm(entities, 34000, 15000, 11000, m_timber, m_site_green)
  draw_coconut_palm(entities, 28000, 25000, 12000, m_timber, m_site_green)
  
  # Bamboo clusters (rear and sides)
  draw_bamboo_cluster(entities, -15000, 32000, 8, m_site_green)
  draw_bamboo_cluster(entities, 0, 34000, 10, m_site_green)
  draw_bamboo_cluster(entities, 15000, 32000, 8, m_site_green)
  draw_bamboo_cluster(entities, -25000, -20000, 6, m_site_green)
  draw_bamboo_cluster(entities, 25000, -20000, 6, m_site_green)
  
  # ----------------------------------------------------
  # STEP 15: SCENE SETUP
  # ----------------------------------------------------
  pages = model.pages
  while pages.count > 0
    pages.erase(pages[0])
  end
  
  def setup_scene(name, eye_coords, target_coords, perspective = true, height = nil)
    model = Sketchup.active_model
    view = model.active_view
    camera = view.camera
    
    camera.perspective = perspective
    if height && !perspective
      camera.height = height
    end
    
    eye = Geom::Point3d.new(eye_coords[0], eye_coords[1], eye_coords[2])
    target = Geom::Point3d.new(target_coords[0], target_coords[1], target_coords[2])
    
    dx = (target.x - eye.x).abs
    dy = (target.y - eye.y).abs
    if dx < 1 && dy < 1
      up = Geom::Vector3d.new(0, 1, 0)
    else
      up = Geom::Vector3d.new(0, 0, 1)
    end
    
    camera.set(eye, target, up)
    
    page = model.pages.add(name)
    page.update(1) # camera flag
    page
  end
  
  # 1. Top View Floor Plan
  setup_scene("Top View Floor Plan", [6100, 8540, 45000], [6100, 8540, 0], false, 24000)
  
  # 2. Aerial 3D View
  setup_scene("Aerial 3D View", [35000, -18000, 20000], [6100, 8540, 1500], true)
  
  # 3. Front Entry View
  setup_scene("Front Entry View", [6100, -12000, 2000], [6100, 2000, 1800], true)
  
  # 4. Courtyard View
  setup_scene("Courtyard View", [6100, 5000, 1600], [6100, 12000, 2200], true)
  
  # 5. Living to Deck View
  setup_scene("Living to Deck View", [7800, 2000, 1600], [3000, -3000, 1000], true)
  
  # 6. Forest Deck View
  setup_scene("Forest Deck View", [6100, -9000, 1500], [6100, 2000, 2200], true)
  
  # 7. Roof + Solar View
  setup_scene("Roof + Solar View", [-10000, 22000, 15000], [6100, 8540, 3000], true)
  
  # 8. Full 1-Acre Site View
  setup_scene("Full 1-Acre Site View", [42000, -30000, 35000], [6100, 8540, 0], true)
  
  # 9. Website Banner Wide View
  setup_scene("Website Banner Wide View", [48000, -25000, 18000], [6100, 8540, 1200], true)
  
  # 10. Night Lighting View
  page_night = setup_scene("Night Lighting View", [22000, -10000, 6000], [6100, 8540, 1500], true)
  
  model.shadow_info["DisplayShadows"] = true
  model.shadow_info["TZOffset"] = 5.5
  model.shadow_info["DateTime"] = Time.utc(2026, 5, 20, 13, 30, 0) # 19:00 IST
  page_night.update(2) # shadow flag
  
  # Reset shadow display default for other pages
  model.shadow_info["DisplayShadows"] = false
  
  # ----------------------------------------------------
  # STEP 16: SAVE UPGRADED MODEL AND EXPORT VISUALS
  # ----------------------------------------------------
  output_dir = "C:/Users/INTEL/Desktop/GOA/WEBSITE/Model/Layout"
  render_dir = File.join(output_dir, "Reserve_Varde_2BHK_Final_Renders")
  Dir.mkdir(render_dir) unless Dir.exist?(render_dir)
  
  upgraded_skp_path = File.join(output_dir, "Reserve_Varde_2BHK_Upgraded_Model.skp")
  status = model.save(upgraded_skp_path)
  puts "Upgraded Model saved successfully: #{status} at #{upgraded_skp_path}"
  
  model.pages.each do |page|
    model.pages.selected_page = page
    
    # Map page name to requested upgraded render filenames
    img_name = case page.name
               when "Top View Floor Plan"
                 # Not explicitly requested in the list, but let's export it as well!
                 "Reserve_Varde_2BHK_Top_View.png"
               when "Aerial 3D View"
                 "Reserve_Varde_2BHK_Aerial_View.png"
               when "Front Entry View"
                 "Reserve_Varde_2BHK_Front_Entry_View.png"
               when "Courtyard View"
                 "Reserve_Varde_2BHK_Courtyard_View.png"
               when "Living to Deck View"
                 "Reserve_Varde_2BHK_Living_Deck_View.png"
               when "Forest Deck View"
                 "Reserve_Varde_2BHK_Forest_Deck_View.png"
               when "Roof + Solar View"
                 "Reserve_Varde_2BHK_Roof_Solar_View.png"
               when "Full 1-Acre Site View"
                 "Reserve_Varde_2BHK_Full_1Acre_Site_View.png"
               when "Night Lighting View"
                 "Reserve_Varde_2BHK_Night_View.png"
               when "Website Banner Wide View"
                 "Reserve_Varde_2BHK_Website_Banner_View.png"
               else
                 "Reserve_Varde_2BHK_#{page.name.gsub(' ', '_')}.png"
               end
               
    img_path = File.join(render_dir, img_name)
    model.active_view.write_image(img_path, 1920, 1080)
    puts "Exported render: #{img_path}"
  end
  
  # ----------------------------------------------------
  # STEP 17: WRITE UPGRADED REPORT
  # ----------------------------------------------------
  report_path = File.join(output_dir, "Reserve_Varde_2BHK_Upgraded_SketchUp_Report.md")
  report_content = <<~REPORT
    # Upgraded Modelling Report — Reserve Varde 2BHK Modular Eco Estate
    
    **Project:** Reserve Varde / Reserva Verde Goa  
    **Model:** 2BHK Compact Modular Eco Estate  
    **Version:** Upgraded Premium Concept  
    **Date:** May 2026  
    
    ## 1. Upgrade File Details
    - **Upgraded SketchUp Model:** `Reserve_Varde_2BHK_Upgraded_Model.skp`
    - **Render Images Folder:** `Reserve_Varde_2BHK_Final_Renders/`
    - **Exported Visuals:**
      1. Aerial 3D View: `Reserve_Varde_2BHK_Aerial_View.png`
      2. Front Entry View: `Reserve_Varde_2BHK_Front_Entry_View.png`
      3. Courtyard View: `Reserve_Varde_2BHK_Courtyard_View.png`
      4. Forest Deck View: `Reserve_Varde_2BHK_Forest_Deck_View.png`
      5. Roof/Solar View: `Reserve_Varde_2BHK_Roof_Solar_View.png`
      6. Full 1-Acre Site View: `Reserve_Varde_2BHK_Full_1Acre_Site_View.png`
      7. Night/Dusk View: `Reserve_Varde_2BHK_Night_View.png`
      8. Top View Floor Plan: `Reserve_Varde_2BHK_Top_View.png` (Included)
      9. Living/Deck View: `Reserve_Varde_2BHK_Living_Deck_View.png` (Included)
    
    ## 2. Upgraded Visual & Material Improvements
    - **Exterior Walls Cladding:** Mixed-material system of Bamboo Cladding (tan wood), Charred Timber (black Shou-sugi-ban) framing the entrance and wing walls, and Ivory Lime Plaster panels.
    - **Base Plinth:** Upgraded Laterite Stone base Z=0 to Z=450 mm.
    - **Timber Privacy Screens:** Vertical timber slat screens (40x60 mm slats at 250 mm spacing) installed around the Master Wing window W01 to block sun and enhance privacy.
    - **Extended Sloped Roof:** Deep roof overhangs extending 1000 mm beyond the container boundaries with dark charcoal metal standing seams and solid charcoal fascia boards.
    - **Gutters & Downpipes:** Rainwater gutters along the courtyard edges connected to four 80 mm diameter downpipes at the courtyard corners.
    - **Central Courtyard Paving & Seating:** Herringbone paved surface with a built-in laterite bench topped with natural wood and white canvas cushions.
    - **Courtyard Reflecting Water Channel:** A sleek 200 mm wide concrete reflecting water channel running through the center of the courtyard to feed the plunge pool.
    - **Multi-Level Forest Deck & Glass Railing:** A teak wood deck equipped with sun loungers, outdoor dining set, and a 1m tall bronze-post glass safety railing.
    - **Goa Tropical Landscaping:** Dense forest boundary trees including detailed curved Coconut Palms, Areca Palms, and Bamboo clusters.
    - **Interiors Visuals:** Modeled TV wood slatted backdrop wall, flat screen TV, dining table with a designer metal pendant light, vanity units, and shower glass doors visible through the glazing.
    
    ## 3. Site Context Details
    - 1-acre plot perimeter with a main entry gate comprising laterite stone piers and a sliding timber gate.
    - Gravel driveway leading to a 2-car parking court.
    - Winding stepping stone paths leading to a dedicated firepit/meditation circle with logs in the rear forest zone.
    
    ## 4. Compliance and Verification Required
    - **Monsoon Flashings:** Verification of flashings and weather seals at the junction between the glass corridors and container modules.
    - **Landscape Maintenance:** Placement of organic mulch around the bamboo clusters to prevent weed growth and coordinate irrigation lines.
    - **Solar Structural Load:** Verification of roof trusses to bear the weight of the solar panels and wind lift coefficients during heavy South Goa monsoons.
  REPORT
  
  File.write(report_path, report_content)
  puts "Upgraded Report written successfully to #{report_path}"
end

begin
  generate_upgraded_model
rescue => e
  File.write("C:/Users/INTEL/Desktop/GOA/WEBSITE/Model/Layout/ruby_error_upgraded.log", "#{e.class}: #{e.message}\n#{e.backtrace.join("\n")}")
ensure
  Sketchup.quit
end
